### ISSUE TITLE
Cannot add group while building cabs

### ISSUE THREAD

**Issue by bennahugo** [SpheMakh/Stimela#103]
After pulling the latest images I run stimela build. Doesn't seem to work. @sphemakh isn't it safer to mount the system shadowers and groups files ro when running the cabs instead of passing ids in?

Running:
bhugo@paul:~$ docker --version
Docker version 1.10.3, build 20f81dd

```
+ stimela build --no-cache
Sending build context to Docker daemon 35.84 kB

Step 1 : FROM stimela/tigger:0.2.8
 ---> 5f7eda48b6e2
Step 2 : MAINTAINER <sphemakh@gmail.com>
 ---> Running in 2c3ea9679b72
 ---> ed8cc53633f6
Removing intermediate container 2c3ea9679b72
Step 3 : ENV MEQTREES_CATTERY_PATH /usr/lib/python2.7/dist-packages/Cattery
 ---> Running in 9608bddaecef
 ---> 3c07dc677362
Removing intermediate container 9608bddaecef
Step 4 : ADD src /code
 ---> bb1e94c60d40
Removing intermediate container 6bde2f82187b
Step 5 : RUN groupadd -g 106 jenkins
 ---> Running in 20d976c3b875
[91mgroupadd: GID '106' already exists
[0mRemoving intermediate container 20d976c3b875
The command '/bin/sh -c groupadd -g 106 jenkins' returned a non-zero code: 4
running: docker build --no-cache --force-rm -f /var/lib/jenkins/jobs/stimela-cron/workspace/14/projects/pyenv/local/lib/python2.7/site-packages/stimela/cargo/cab/specfit/tmpFGTI7u -t jenkins_cab/specfit /var/lib/jenkins/jobs/stimela-cron/workspace/14/projects/pyenv/local/lib/python2.7/site-packages/stimela/cargo/cab/specfit
Traceback (most recent call last):
  File "/var/lib/jenkins/jobs/stimela-cron/workspace/14/projects/pyenv/bin/stimela", line 13, in <module>
    stimela.main([a for a in sys.argv[1:]])
  File "/var/lib/jenkins/jobs/stimela-cron/workspace/14/projects/pyenv/local/lib/python2.7/site-packages/stimela/__init__.py", line 522, in main
    _cmd(argv)
  File "/var/lib/jenkins/jobs/stimela-cron/workspace/14/projects/pyenv/local/lib/python2.7/site-packages/stimela/__init__.py", line 134, in build
    build_args=build_args, args=no_cache)
  File "/var/lib/jenkins/jobs/stimela-cron/workspace/14/projects/pyenv/local/lib/python2.7/site-packages/stimela/docker.py", line 37, in build
    build_path])
  File "/var/lib/jenkins/jobs/stimela-cron/workspace/14/projects/pyenv/local/lib/python2.7/site-packages/stimela/utils/__init__.py", line 72, in xrun
    raise SystemError('%s: returns errr code %d'%(command, process.returncode))
SystemError: docker build: returns errr code 1
Build step 'Execute shell' marked build as failure
Warning: you have no plugins providing access control for builds, so falling back to legacy behavior of permitting any downstream builds to be triggered
Triggering a new build of Docker-killswitch
Finished: FAILURE
```

**Comment by SpheMakh** [comment]
Fixed in PR #109
