### ISSUE TITLE
New owlcat missing astropy.io

### ISSUE THREAD

**Issue by bennahugo** [SpheMakh/Stimela#104]
running: docker start -a fitstool-140000310050408148950592671
Traceback (most recent call last):
  File "/usr/local/bin/fitstool.py", line 29, in <module>
    from Owlcat.FitsTool import main
  File "/usr/local/lib/python2.7/dist-packages/Owlcat/FitsTool.py", line 35, in <module>
    from astropy.io import fits as pyfits
ImportError: No module named astropy.io

**Comment by SpheMakh** [comment]
Fixed in Owlcat
