### ISSUE TITLE
bitwise or assignment

### ISSUE THREAD

**Issue by bennahugo** [SpheMakh/Stimela#110]
@SpheMakh thought this one was fixed?

```
.0019 0.0015 0.0011 0.00085 0.00064 0.00048 0.00036 0.00027 0.00021 0.00018 0.00017 0.00015 0.00014 0.00014 0.00013 0.00012 0.00011 0.0001 9.6e-05 9e-05
3788.57 20.1Gb gainopts(StefCal.py:1393:run_gain_solution): flagged gains per antenna: 01 240.00%, 02 240.00%, 03 240.00%, 04 240.00%, 05 1800.00%, 06 240.00%, 07 360.00%, 08 360.00%, 09 360.00%, 10 600.00%, 13 360.00%, 14 1560.00%, 15 360.00%, 16 480.00%, 18 240.00%, 
19 1200.00%, 21 360.00%, 24 1560.00%, 25 120.00%
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/Cattery/Calico/OMS/StefCal/StefCal.py", line 783, in get_result
    flagged |= self.run_gain_solution(opt,model,data,weight,bitflags,flag_null_gains=True,looptype=looptype);
  File "/usr/local/lib/python2.7/dist-packages/Cattery/Calico/OMS/StefCal/StefCal.py", line 1396, in run_gain_solution
    fmask |= gainflags.get(pq[1],0);
TypeError: ufunc 'bitwise_or' output (typecode 'l') could not be coerced to provided output parameter (typecode '?') according to the casting rule ''same_kind''
3.0Gb meqserver(meqserver.py:288:stop_default_mqs): meqserver not exited yet, waiting another 10 seconds
### Job result: None
### No more commands
### meqserver reported 33 error(s) during the run:
###   000: node 'stefcal': <2 exceptions> (while getting result for request ev.0.0.0.0.1)
###   001: node 'VisDataMux': error processing tile 0.0.0.0.1.1
###   002: node 'stefcal': <2 exceptions> (while getting result for request ev.0.0.0.2.1)
###   003: node 'VisDataMux': error processing tile 0.0.0.0.1.3
###   004: node 'stefcal': <2 exceptions> (while getting result for request ev.0.0.0.4.1)
###   005: node 'VisDataMux': error processing tile 0.0.0.0.1.5
###   006: node 'stefcal': <2 exceptions> (while getting result for request ev.0.0.0.6.1)
###   007: node 'VisDataMux': error processing tile 0.0.0.0.1.7
###   008: node 'stefcal': <2 exceptions> (while getting result for request ev.0.0.0.7.1)
###   009: node 'VisDataMux': error processing tile 0.0.0.0.1.8
###   010: node 'stefcal': <2 exceptions> (while getting result for request ev.0.0.0.9.1)
###   011: node 'VisDataMux': error processing tile 0.0.0.0.1.10
###   012: node 'stefcal': <2 exceptions> (while getting result for request ev.0.0.0.11.1)
###   013: node 'VisDataMux': error processing tile 0.0.0.0.1.12
###   014: node 'stefcal': <2 exceptions> (while getting result for request ev.0.0.0.12.1)
###   015: node 'VisDataMux': error processing tile 0.0.0.0.1.13
###   016: node 'stefcal': <2 exceptions> (while getting result for request ev.0.0.0.14.1)
###   017: node 'VisDataMux': error processing tile 0.0.0.0.1.15
###   018: node 'stefcal': <2 exceptions> (while getting result for request ev.0.0.0.17.1)
###   019: node 'VisDataMux': error processing tile 0.0.0.0.1.18
###   020: node 'stefcal': <2 exceptions> (while getting result for request ev.0.0.0.18.1)
###   021: node 'VisDataMux': error processing tile 0.0.0.0.1.19
###   022: node 'stefcal': <2 exceptions> (while getting result for request ev.0.0.0.19.1)
###   023: node 'VisDataMux': error processing tile 0.0.0.0.1.20
###   024: node 'stefcal': <2 exceptions> (while getting result for request ev.0.0.0.24.1)
###   025: node 'VisDataMux': error processing tile 0.0.0.0.1.25
###   026: node 'stefcal': <2 exceptions> (while getting result for request ev.0.0.0.25.1)
###   027: node 'VisDataMux': error processing tile 0.0.0.0.1.26
###   028: node 'stefcal': <2 exceptions> (while getting result for request ev.0.0.0.26.1)
###   029: node 'VisDataMux': error processing tile 0.0.0.0.1.27
###   030: node 'stefcal': <2 exceptions> (while getting result for request ev.0.0.0.27.1)
###   031: node 'VisDataMux': error processing footer 0.0.0
###   032: node 'VisDataMux': execute() failed: ufunc 'bitwise_or' output (typecode 'l') could not be coerced to provided output parameter (typecode '?') according to the casting rule ''same_kind'' (return code 0x810021)
### Stopping the meqserver
### All your batch are not belong to us, returning with error code
Traceback (most recent call last):
  File "/code/run.py", line 205, in <module>
    run_meqtrees(msname)
  File "/code/run.py", line 173, in run_meqtrees
running: /usr/bin/meqtree-pipeliner.py --mt 16 -c /code/tdlconf.profiles [stefcal] ms_sel.input_column=DATA ms_sel.field_index=1 ms_sel.msname=/home/hugo/msdir/12A-405.sb7601493.eb10633016.56086.127048738424.ms stefcal_diffgain.freqsmooth=1 stefcal_gain.table=/home/hug
o/msdir/12A-405.sb7601493.eb10633016.56086.127048738424.ms/12A-405.sb7601493.eb10633016.56086.127048738424-cal1.gain.cp me.e_module=Siamese_OMS_pybeams_fits pybeams_fits.m_axis=Y tiggerlsm.lsm_subset=all stefcal_gain.freqint=8 pybeams_fits.filename_pattern='/input/beam
s/JVLA-L-centred-$(corr)_$(reim).fits' stefcal_gain.flag_chisq=1 do_output=CORR_RES stefcal_gain.flag_ampl=1 ms_sel.ddid_index=0 ms_sel.tile_size=128 stefcal_diffgain.timesmooth=1 pybeams_fits.l_axis=-X ms_rfl.read_flagsets=-stefcal me.e_enable=1 me.p_enable=1 stefcal_
gain.implementation=Gain2x2 stefcal_gain.flag_chisq_threshold=10 ms_rfl.read_legacy_flags=1 stefcal_gain.flag_ampl_low=0.15 me.e_all_stations=1 ms_sel.ms_corr_sel='2x2' stefcal_gain.flag_ampl_high=2.8 stefcal_gain.mode=solve-save tiggerlsm.filename=/home/hugo/output/vl
a_NGC417_LBand.lsm1master.lsm.html stefcal_gain.timeint=24 ms_sel.output_column=CORRECTED_DATA /usr/local/lib/python2.7/dist-packages/Cattery/Calico/calico-stefcal.py =stefcal
    utils.xrun(cab['binary'], args + ['-s {}'.format(saveconf) if saveconf else ''])
  File "/utils/utils/__init__.py", line 72, in xrun
    raise SystemError('%s: returns errr code %d'%(command, process.returncode))
SystemError: /usr/bin/meqtree-pipeliner.py: returns errr code 1
```

**Comment by bennahugo** [comment]
Dont think the 0.2.8 meqtrees container is using the correct cattery. Think we definitely need to rm the system cattery

**Comment by bennahugo** [comment]
No sorry see it is still there must be a bug in calico

**Comment by bennahugo** [comment]
To be more specific
https://github.com/ska-sa/meqtrees-cattery/blob/master/Cattery/Calico/OMS/StefCal/StefCal.py#L1389
This gets triggered obviously when amplitude clipping is enabled which is necessary in the 2x2 ap case. What is even more of a headache it doesn't show up till 3788 seconds passed

**Comment by SpheMakh** [comment]
I wasn't entirely happy with the fix. Will do some thorough debugging today to see what causes this, instead of implementing a workaround.

**Comment by SpheMakh** [comment]
But, I'm going to move to this to cattery, where it belongs.  see https://github.com/ska-sa/meqtrees-cattery/issues/66
