### ISSUE TITLE
Error when pulling docker images

### ISSUE THREAD

**Issue by Luke-Pratley** [SpheMakh/Stimela#124]
I just [installed](https://github.com/SpheMakh/Stimela/wiki/Installation) stimela, but I run into an error with my own system when it tries to pull the docker images. 

I have minimal experience with docker, so this could be a problem on my end. This is the output from stimela:
``` 
$ stimela pull                                                                                                                             
running: docker pull stimela/tigger:0.2.8
Warning: failed to get default registry endpoint from daemon (Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?). Using system default: https://index.docker.io/v1/
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
Traceback (most recent call last):
  File "/usr/local/bin/stimela", line 13, in <module>
    stimela.main([a for a in sys.argv[1:]])
  File "/usr/local/lib/python2.7/site-packages/stimela/__init__.py", line 522, in main
    _cmd(argv)
  File "/usr/local/lib/python2.7/site-packages/stimela/__init__.py", line 267, in pull
    docker.pull(image)
  File "/usr/local/lib/python2.7/site-packages/stimela/docker.py", line 49, in pull
    utils.xrun("docker pull", [image])
  File "/usr/local/lib/python2.7/site-packages/stimela/utils/__init__.py", line 72, in xrun
    raise SystemError('%s: returns errr code %d'%(command, process.returncode))
SystemError: docker pull: returns errr code 1
```

**Comment by Luke-Pratley** [comment]
Hi @ratt-priv-ci , thanks for the clue. It turns out it is because using docker on mac osx has extra steps. I have been able to download the images fine after realising this.

However, I do get an error from Stimela when trying one of your scripts. There is a problem with `ImportError: No module named utils`:
```
$ python ska_coverage.py                                                                                                                                                                                                                                                                                                                                                                                                                                              
INFO:STIMELA:Adding cab 'luke_cab/simms' to recipe. The container will be named 'simms_example-4417907088149303835636'
INFO:STIMELA:Adding cab 'luke_cab/simulator' to recipe. The container will be named 'simulator_example-4417878760149303835656'
INFO:STIMELA:Adding cab 'luke_cab/wsclean' to recipe. The container will be named 'imager_example-4417908048149303835682'
INFO:root:Validating parameters...       CAB = simms
INFO:root:Parameters validated and saved. Parameter file is: stimela_parameter_files/simms_example-4417907088149303835636.json
INFO:STIMELA:Running Container simms_example-4417907088149303835636
INFO:STIMELA:STEP 1 :: Creating MS
INFO:STIMELA:Instantiating container [simms_example-4417907088149303835636]. The container ID is printed below.
running: docker create  -v /usr/local/lib/python2.7/site-packages/stimela:/utils:ro -v /Users/luke/Radio_Data/stimela_parameter_files:/configs:ro -v /Users/luke/Radio_Data/msdir-ska1mid:/home/luke/msdir:rw -v /Users/luke/Radio_Data/input-ska1mid:/input:ro -v /Users/luke/Radio_Data/output-ska1mid:/home/luke/output:rw  -e CONFIG=/configs/simms_example-4417907088149303835636.json -e MSDIR=/home/luke/msdir -e INPUT=/input -e OUTPUT=/home/luke/output  --name simms_example-4417907088149303835636 --shm-size 1gb luke_cab/simms
8ef71f64a33aef31a40a4bdf45e6511f7c5449052e116e3de0746cb3959f2a03
running: docker start -a simms_example-4417907088149303835636
Traceback (most recent call last):
  File "/code/run.py", line 6, in <module>
    import utils
ImportError: No module named utils
INFO:STIMELA:Recipe execution failed while running container simms_example-4417907088149303835636
INFO:STIMELA:Completed containers : []
INFO:STIMELA:Remaining containers : ['simulator_example-4417878760149303835656', 'imager_example-4417908048149303835682']
INFO:STIMELA:Logging remaining task: Simulating visibilities
INFO:STIMELA:Logging remaining task: Imaging MS
INFO:STIMELA:Saving pipeline information in .last_ska1mid_simulation_example.json
INFO:STIMELA:Container simms_example-4417907088149303835636 has been stopped.
running: docker rm simms_example-4417907088149303835636
simms_example-4417907088149303835636
Traceback (most recent call last):
  File "ska_coverage.py", line 74, in <module>
    pipeline.run()
  File "/usr/local/lib/python2.7/site-packages/stimela/recipe.py", line 325, in run
    container.start()
  File "/usr/local/lib/python2.7/site-packages/stimela/docker.py", line 153, in start
    utils.xrun("docker", ["start", "-a", self.name])
  File "/usr/local/lib/python2.7/site-packages/stimela/utils/__init__.py", line 72, in xrun
    raise SystemError('%s: returns errr code %d'%(command, process.returncode))
stimela.recipe.PipelineException: Exception occurred while running pipeline component 'Creating MS': docker: returns errr code 1
```

**Comment by SpheMakh** [comment]
Hey Luke. The standard way of running a stimela script is 

```
stimela run <script name>
```

I'm not entirely sure this will fix your problem. But lets get this out of the way.

Also, run ` $ stimela` without any arguments or `$stimela help` to get some help on the functions

**Comment by SpheMakh** [comment]
Closing this till further notice
