### ISSUE TITLE
Regression in CASA flagdata

### ISSUE THREAD

**Issue by bennahugo** [SpheMakh/Stimela#166]
Bit puzzling. Getting:
```
=========================================
The start-up time of CASA may vary
depending on whether the shared libraries
are cached or not.
=========================================

setgpid( ) failed: Operation not permitted
                   processes may be left dangling...
CASA Version 4.7.0-REL (r38335)
  Compiled on: Wed 2016/09/28 11:50:32 UTC
Traceback (most recent call last):
  File "/casa-release-4.7.0-el6/lib/python2.7/casapy.py", line 475, in <module>
    from taskinit import *
  File "/casa-release-4.7.0-el6/lib/python2.7/taskinit.py", line 1, in <module>
    import pCASA
  File "/casa-release-4.7.0-el6/lib/python2.7/pCASA.py", line 51, in <module>
    import parallel_go
  File "/casa-release-4.7.0-el6/lib/python2.7/parallel_go.py", line 2, in <module>
    if not MPIEnvironment.is_mpi_enabled: from IPython.kernel import client
  File "/casa-release-4.7.0-el6/lib/python2.7/site-packages/IPython/kernel/client.py", line 38, in <module>
    from IPython.kernel.clientconnector import ClientConnector
  File "/casa-release-4.7.0-el6/lib/python2.7/site-packages/IPython/kernel/clientconnector.py", line 22, in <module>
    from IPython.kernel.config import config_manager as kernel_config_manager
  File "/casa-release-4.7.0-el6/lib/python2.7/site-packages/IPython/kernel/config/__init__.py", line 28, in <module>
    security_dir = get_security_dir()
  File "/casa-release-4.7.0-el6/lib/python2.7/site-packages/IPython/genutils.py", line 1015, in get_security_dir
    os.mkdir(security_dir, 0700)
OSError: [Errno 13] Permission denied: '/root/.casa/ipython/security'
Reloaded configurationTraceback (most recent call last):
  File "/code/run.py", line 5, in <module>
    casa = drivecasa.Casapy(log2term=True, echo_to_stdout=True, timeout=24*3600*10)
  File "/usr/local/lib/python2.7/dist-packages/drivecasa/interface.py", line 146, in __init__
    self.child.expect(self.prompt, timeout=60)
  File "/usr/local/lib/python2.7/dist-packages/pexpect/spawnbase.py", line 321, in expect
    timeout, searchwindowsize, async)
  File "/usr/local/lib/python2.7/dist-packages/pexpect/spawnbase.py", line 345, in expect_list
    return exp.expect_loop(timeout)
  File "/usr/local/lib/python2.7/dist-packages/pexpect/expect.py", line 105, in expect_loop
    return self.eof(e)
  File "/usr/local/lib/python2.7/dist-packages/pexpect/expect.py", line 50, in eof
    raise EOF(msg)
pexpect.exceptions.EOF: End Of File (EOF). Braindead platform.
<pexpect.pty_spawn.spawn object at 0x7f2bff3ec4d0>
command: /casa-release-4.7.0-el6/bin/casa
args: ['/casa-release-4.7.0-el6/bin/casa', '--nologger', '--nogui', '--colors=NoColor', '--log2term']
buffer (last 100 chars): ''
before (last 100 chars): "0700)\r\nOSError: [Errno 13] Permission denied: '/root/.casa/ipython/security'\r\nReloaded configuration"
after: <class 'pexpect.exceptions.EOF'>
match: None  
match_index: None
exitstatus: 1
flag_eof: True
pid: 22
child_fd: 5  
closed: False
timeout: 864000
delimiter: <class 'pexpect.exceptions.EOF'>
logfile: None
logfile_read: <open file '<stdout>', mode 'w' at 0x7f2c01576150>
logfile_send: None
maxread: 2000
ignorecase: False
searchwindowsize: None
delaybeforesend: 0.05
delayafterclose: 0.1
delayafterterminate: 0.1
searcher: searcher_re:
    0: re.compile("CASA <[0-9]+>:")
```
when I do
```
154             recipe.add("cab/casa_flagdata", labeller("unflag", line, conf, ms),
155                        {
156                            "msname": os.path.join(line, conf, ms),
157                            "mode": "unflag"
158                        },
159                        input=INPUT, output=OUTPUT,
160                        label=labeller("unflag",line,conf,ms))
```
@SpheMakh May be a permissions error? This was working in 0.2.8

**Comment by bennahugo** [comment]
full log:
```
2017-08-10 10:57:59,451 - STIMELA - INFO - ---------------------------------
2017-08-10 10:57:59,451 - STIMELA - INFO - Stimlela version 0.3.0
2017-08-10 10:57:59,452 - STIMELA - INFO - Sphesihle Makhathini <sphemakh@gmail.com>
2017-08-10 10:57:59,452 - STIMELA - INFO - Running: REDUCE ABEL 781
2017-08-10 10:57:59,452 - STIMELA - INFO - ---------------------------------
2017-08-10 10:57:59,952 - STIMELA - INFO - Adding cab 'bhugo_cab/casa_flagdata' to recipe. The container will be named 'unflag_92CM_96m_11201063_S0_T0_MS'
INFO:STIMELA:Adding cab 'bhugo_cab/casa_flagdata' to recipe. The container will be named 'unflag_92CM_96m_11201063_S0_T0_MS'
2017-08-10 10:58:00,443 - STIMELA - INFO - Adding cab 'bhugo_cab/casa_flagdata' to recipe. The container will be named 'unflag_92CM_96m_11201064_S0_T0_MS'
INFO:STIMELA:Adding cab 'bhugo_cab/casa_flagdata' to recipe. The container will be named 'unflag_92CM_96m_11201064_S0_T0_MS'
2017-08-10 10:58:00,935 - STIMELA - INFO - Adding cab 'bhugo_cab/casa_flagdata' to recipe. The container will be named 'unflag_92CM_96m_11201065_S0_T0_MS'
INFO:STIMELA:Adding cab 'bhugo_cab/casa_flagdata' to recipe. The container will be named 'unflag_92CM_96m_11201065_S0_T0_MS'
2017-08-10 10:58:01,427 - STIMELA - INFO - Adding cab 'bhugo_cab/casa_flagdata' to recipe. The container will be named 'unflag_92CM_96m_11201065_S0_T1_MS'
INFO:STIMELA:Adding cab 'bhugo_cab/casa_flagdata' to recipe. The container will be named 'unflag_92CM_96m_11201065_S0_T1_MS'
2017-08-10 10:58:01,920 - STIMELA - INFO - Adding cab 'bhugo_cab/casa_flagdata' to recipe. The container will be named 'unflag_92CM_96m_11201065_S0_T10_MS'
INFO:STIMELA:Adding cab 'bhugo_cab/casa_flagdata' to recipe. The container will be named 'unflag_92CM_96m_11201065_S0_T10_MS'
2017-08-10 10:58:02,415 - STIMELA - INFO - Adding cab 'bhugo_cab/casa_flagdata' to recipe. The container will be named 'unflag_92CM_96m_11201065_S0_T11_MS'
INFO:STIMELA:Adding cab 'bhugo_cab/casa_flagdata' to recipe. The container will be named 'unflag_92CM_96m_11201065_S0_T11_MS'
2017-08-10 10:58:02,922 - STIMELA - INFO - Adding cab 'bhugo_cab/casa_flagdata' to recipe. The container will be named 'unflag_92CM_96m_11201065_S0_T12_MS'
INFO:STIMELA:Adding cab 'bhugo_cab/casa_flagdata' to recipe. The container will be named 'unflag_92CM_96m_11201065_S0_T12_MS'
2017-08-10 10:58:03,416 - STIMELA - INFO - Adding cab 'bhugo_cab/casa_flagdata' to recipe. The container will be named 'unflag_92CM_96m_11201065_S0_T13_MS'
INFO:STIMELA:Adding cab 'bhugo_cab/casa_flagdata' to recipe. The container will be named 'unflag_92CM_96m_11201065_S0_T13_MS'
2017-08-10 10:58:03,911 - STIMELA - INFO - Adding cab 'bhugo_cab/casa_flagdata' to recipe. The container will be named 'unflag_92CM_96m_11201065_S0_T14_MS'
INFO:STIMELA:Adding cab 'bhugo_cab/casa_flagdata' to recipe. The container will be named 'unflag_92CM_96m_11201065_S0_T14_MS'
2017-08-10 10:58:04,401 - STIMELA - INFO - Adding cab 'bhugo_cab/casa_flagdata' to recipe. The container will be named 'unflag_92CM_96m_11201065_S0_T2_MS'
INFO:STIMELA:Adding cab 'bhugo_cab/casa_flagdata' to recipe. The container will be named 'unflag_92CM_96m_11201065_S0_T2_MS'
2017-08-10 10:58:04,892 - STIMELA - INFO - Adding cab 'bhugo_cab/casa_flagdata' to recipe. The container will be named 'unflag_92CM_96m_11201065_S0_T3_MS'
INFO:STIMELA:Adding cab 'bhugo_cab/casa_flagdata' to recipe. The container will be named 'unflag_92CM_96m_11201065_S0_T3_MS'
2017-08-10 10:58:05,385 - STIMELA - INFO - Adding cab 'bhugo_cab/casa_flagdata' to recipe. The container will be named 'unflag_92CM_96m_11201065_S0_T4_MS'
INFO:STIMELA:Adding cab 'bhugo_cab/casa_flagdata' to recipe. The container will be named 'unflag_92CM_96m_11201065_S0_T4_MS'
2017-08-10 10:58:05,876 - STIMELA - INFO - Adding cab 'bhugo_cab/casa_flagdata' to recipe. The container will be named 'unflag_92CM_96m_11201065_S0_T5_MS'
INFO:STIMELA:Adding cab 'bhugo_cab/casa_flagdata' to recipe. The container will be named 'unflag_92CM_96m_11201065_S0_T5_MS'
2017-08-10 10:58:06,377 - STIMELA - INFO - Adding cab 'bhugo_cab/casa_flagdata' to recipe. The container will be named 'unflag_92CM_96m_11201065_S0_T6_MS'
INFO:STIMELA:Adding cab 'bhugo_cab/casa_flagdata' to recipe. The container will be named 'unflag_92CM_96m_11201065_S0_T6_MS'
2017-08-10 10:58:06,872 - STIMELA - INFO - Adding cab 'bhugo_cab/casa_flagdata' to recipe. The container will be named 'unflag_92CM_96m_11201065_S0_T7_MS'
INFO:STIMELA:Adding cab 'bhugo_cab/casa_flagdata' to recipe. The container will be named 'unflag_92CM_96m_11201065_S0_T7_MS'
2017-08-10 10:58:07,368 - STIMELA - INFO - Adding cab 'bhugo_cab/casa_flagdata' to recipe. The container will be named 'unflag_92CM_96m_11201065_S0_T8_MS'
INFO:STIMELA:Adding cab 'bhugo_cab/casa_flagdata' to recipe. The container will be named 'unflag_92CM_96m_11201065_S0_T8_MS'
2017-08-10 10:58:07,861 - STIMELA - INFO - Adding cab 'bhugo_cab/casa_flagdata' to recipe. The container will be named 'unflag_92CM_96m_11201065_S0_T9_MS'
INFO:STIMELA:Adding cab 'bhugo_cab/casa_flagdata' to recipe. The container will be named 'unflag_92CM_96m_11201065_S0_T9_MS'
2017-08-10 10:58:08,353 - STIMELA - INFO - Adding cab 'bhugo_cab/casa_flagdata' to recipe. The container will be named 'unflag_92CM_96m_11201066_S0_T0_MS'
INFO:STIMELA:Adding cab 'bhugo_cab/casa_flagdata' to recipe. The container will be named 'unflag_92CM_96m_11201066_S0_T0_MS'
2017-08-10 10:58:08,844 - STIMELA - INFO - Adding cab 'bhugo_cab/casa_flagdata' to recipe. The container will be named 'unflag_92CM_96m_11201067_S0_T0_MS'
INFO:STIMELA:Adding cab 'bhugo_cab/casa_flagdata' to recipe. The container will be named 'unflag_92CM_96m_11201067_S0_T0_MS'
2017-08-10 10:58:09,339 - STIMELA - INFO - Adding cab 'bhugo_cab/casa_flagdata' to recipe. The container will be named 'unflag_21CM_54m_11202011_S0_T0_MS'
INFO:STIMELA:Adding cab 'bhugo_cab/casa_flagdata' to recipe. The container will be named 'unflag_21CM_54m_11202011_S0_T0_MS'
2017-08-10 10:58:09,834 - STIMELA - INFO - Adding cab 'bhugo_cab/casa_flagdata' to recipe. The container will be named 'unflag_21CM_54m_11202012_S0_T0_MS'
INFO:STIMELA:Adding cab 'bhugo_cab/casa_flagdata' to recipe. The container will be named 'unflag_21CM_54m_11202012_S0_T0_MS'
2017-08-10 10:58:10,337 - STIMELA - INFO - Adding cab 'bhugo_cab/casa_flagdata' to recipe. The container will be named 'unflag_21CM_54m_11202013_S0_T0_MS'
INFO:STIMELA:Adding cab 'bhugo_cab/casa_flagdata' to recipe. The container will be named 'unflag_21CM_54m_11202013_S0_T0_MS'
2017-08-10 10:58:10,830 - STIMELA - INFO - Adding cab 'bhugo_cab/casa_flagdata' to recipe. The container will be named 'unflag_21CM_54m_11202013_S0_T1_MS'
INFO:STIMELA:Adding cab 'bhugo_cab/casa_flagdata' to recipe. The container will be named 'unflag_21CM_54m_11202013_S0_T1_MS'
2017-08-10 10:58:11,325 - STIMELA - INFO - Adding cab 'bhugo_cab/casa_flagdata' to recipe. The container will be named 'unflag_21CM_54m_11202013_S0_T2_MS'
INFO:STIMELA:Adding cab 'bhugo_cab/casa_flagdata' to recipe. The container will be named 'unflag_21CM_54m_11202013_S0_T2_MS'
2017-08-10 10:58:11,817 - STIMELA - INFO - Adding cab 'bhugo_cab/casa_flagdata' to recipe. The container will be named 'unflag_21CM_54m_11202014_S0_T0_MS'
INFO:STIMELA:Adding cab 'bhugo_cab/casa_flagdata' to recipe. The container will be named 'unflag_21CM_54m_11202014_S0_T0_MS'
2017-08-10 10:58:12,313 - STIMELA - INFO - Adding cab 'bhugo_cab/casa_flagdata' to recipe. The container will be named 'unflag_21CM_54m_11202015_S0_T0_MS'
INFO:STIMELA:Adding cab 'bhugo_cab/casa_flagdata' to recipe. The container will be named 'unflag_21CM_54m_11202015_S0_T0_MS'
2017-08-10 10:58:12,313 - STIMELA - INFO - Running job unflag_92CM_96m_11201063_S0_T0_MS
INFO:STIMELA:Running job unflag_92CM_96m_11201063_S0_T0_MS
2017-08-10 10:58:12,314 - STIMELA - INFO - STEP 1 :: unflag_92CM_96m_11201063_S0_T0_MS
INFO:STIMELA:STEP 1 :: unflag_92CM_96m_11201063_S0_T0_MS
INFO:root:Validating parameters...       CAB = casa_flagdata
INFO:root:Parameters validated and saved. Parameter file is: stimela_parameter_files/unflag_92CM_96m_11201063_S0_T0_MS-140584951238472150236267965.json
2017-08-10 10:58:12,318 - STIMELA - INFO - Instantiating container [unflag_92CM_96m_11201063_S0_T0_MS-140584951238472150236267965]. The container ID is printed below.
INFO:STIMELA:Instantiating container [unflag_92CM_96m_11201063_S0_T0_MS-140584951238472150236267965]. The container ID is printed below.
running: docker create --user 1004  -v /data/bhugo/stimela/local/lib/python2.7/site-packages/stimela:/utils:ro -v /data/bhugo/stimela_parameter_files:/configs:ro -v /etc/group:/etc/group:ro -v /etc/passwd:/etc/passwd:ro -v /etc/shadow:/etc/shadow:ro -v /etc/sudoers.d:/etc/sudoers.d:ro -v /data/bhugo/msdir/A781:/home/bhugo/msdir:rw -v /data/bhugo/input:/input:ro -v /data/bhugo/output:/home/bhugo/output:rw  -e CONFIG=/configs/unflag_92CM_96m_11201063_S0_T0_MS-140584951238472150236267965.json -e MSDIR=/home/bhugo/msdir -e INPUT=/input -e OUTPUT=/home/bhugo/output -e LOGFILE=/home/bhugo/output/log-unflag_92CM_96m_11201063_S0_T0_MS.txt  --name unflag_92CM_96m_11201063_S0_T0_MS-140584951238472150236267965 --shm-size 1gb bhugo_cab/casa_flagdata 
b148758a70de9b6b687b40cf7eb91d40027ac1a73302aa3b19fb7de11810dc2b
running: docker start -a unflag_92CM_96m_11201063_S0_T0_MS-140584951238472150236267965

=========================================
The start-up time of CASA may vary
depending on whether the shared libraries
are cached or not.
=========================================

setgpid( ) failed: Operation not permitted
                   processes may be left dangling...
CASA Version 4.7.0-REL (r38335)
  Compiled on: Wed 2016/09/28 11:50:32 UTC
Traceback (most recent call last):
  File "/casa-release-4.7.0-el6/lib/python2.7/casapy.py", line 475, in <module>
    from taskinit import *
  File "/casa-release-4.7.0-el6/lib/python2.7/taskinit.py", line 1, in <module>
    import pCASA
  File "/casa-release-4.7.0-el6/lib/python2.7/pCASA.py", line 51, in <module>
    import parallel_go
  File "/casa-release-4.7.0-el6/lib/python2.7/parallel_go.py", line 2, in <module>
    if not MPIEnvironment.is_mpi_enabled: from IPython.kernel import client
  File "/casa-release-4.7.0-el6/lib/python2.7/site-packages/IPython/kernel/client.py", line 38, in <module>
    from IPython.kernel.clientconnector import ClientConnector
  File "/casa-release-4.7.0-el6/lib/python2.7/site-packages/IPython/kernel/clientconnector.py", line 22, in <module>
    from IPython.kernel.config import config_manager as kernel_config_manager
  File "/casa-release-4.7.0-el6/lib/python2.7/site-packages/IPython/kernel/config/__init__.py", line 28, in <module>
    security_dir = get_security_dir()
  File "/casa-release-4.7.0-el6/lib/python2.7/site-packages/IPython/genutils.py", line 1015, in get_security_dir
    os.mkdir(security_dir, 0700)
OSError: [Errno 13] Permission denied: '/root/.casa/ipython/security'
Reloaded configuration
Traceback (most recent call last):
  File "/code/run.py", line 5, in <module>
    casa = drivecasa.Casapy(log2term=True, echo_to_stdout=True, timeout=24*3600*10)
  File "/usr/local/lib/python2.7/dist-packages/drivecasa/interface.py", line 146, in __init__
    self.child.expect(self.prompt, timeout=60)
  File "/usr/local/lib/python2.7/dist-packages/pexpect/spawnbase.py", line 321, in expect
    timeout, searchwindowsize, async)
  File "/usr/local/lib/python2.7/dist-packages/pexpect/spawnbase.py", line 345, in expect_list
    return exp.expect_loop(timeout)
  File "/usr/local/lib/python2.7/dist-packages/pexpect/expect.py", line 105, in expect_loop
    return self.eof(e)
  File "/usr/local/lib/python2.7/dist-packages/pexpect/expect.py", line 50, in eof
    raise EOF(msg)
pexpect.exceptions.EOF: End Of File (EOF). Braindead platform.
<pexpect.pty_spawn.spawn object at 0x7f1f199484d0>
command: /casa-release-4.7.0-el6/bin/casa
args: ['/casa-release-4.7.0-el6/bin/casa', '--nologger', '--nogui', '--colors=NoColor', '--log2term']
buffer (last 100 chars): ''
before (last 100 chars): "00)\r\nOSError: [Errno 13] Permission denied: '/root/.casa/ipython/security'\r\nReloaded configuration\r\n"
after: <class 'pexpect.exceptions.EOF'>
match: None
match_index: None
exitstatus: 1
flag_eof: True
pid: 21
child_fd: 5
closed: False
timeout: 864000
delimiter: <class 'pexpect.exceptions.EOF'>
logfile: None
logfile_read: <open file '<stdout>', mode 'w' at 0x7f1f1bad2150>
logfile_send: None
maxread: 2000
ignorecase: False
searchwindowsize: None
delaybeforesend: 0.05
delayafterclose: 0.1
delayafterterminate: 0.1
searcher: searcher_re:
    0: re.compile("CASA <[0-9]+>:")
2017-08-10 10:58:15,743 - STIMELA - INFO - Recipe execution failed while running job unflag_92CM_96m_11201063_S0_T0_MS
INFO:STIMELA:Recipe execution failed while running job unflag_92CM_96m_11201063_S0_T0_MS
2017-08-10 10:58:15,744 - STIMELA - INFO - Completed jobs : []
INFO:STIMELA:Completed jobs : []
2017-08-10 10:58:15,745 - STIMELA - INFO - Remaining jobs : ['unflag_92CM_96m_11201064_S0_T0_MS', 'unflag_92CM_96m_11201065_S0_T0_MS', 'unflag_92CM_96m_11201065_S0_T1_MS', 'unflag_92CM_96m_11201065_S0_T10_MS', 'unflag_92CM_96m_11201065_S0_T11_MS', 'unflag_92CM_96m_11201065_S0_T12_MS', 'unflag_92CM_96m_11201065_S0_T13_MS', 'unflag_92CM_96m_11201065_S0_T14_MS', 'unflag_92CM_96m_11201065_S0_T2_MS', 'unflag_92CM_96m_11201065_S0_T3_MS', 'unflag_92CM_96m_11201065_S0_T4_MS', 'unflag_92CM_96m_11201065_S0_T5_MS', 'unflag_92CM_96m_11201065_S0_T6_MS', 'unflag_92CM_96m_11201065_S0_T7_MS', 'unflag_92CM_96m_11201065_S0_T8_MS', 'unflag_92CM_96m_11201065_S0_T9_MS', 'unflag_92CM_96m_11201066_S0_T0_MS', 'unflag_92CM_96m_11201067_S0_T0_MS', 'unflag_21CM_54m_11202011_S0_T0_MS', 'unflag_21CM_54m_11202012_S0_T0_MS', 'unflag_21CM_54m_11202013_S0_T0_MS', 'unflag_21CM_54m_11202013_S0_T1_MS', 'unflag_21CM_54m_11202013_S0_T2_MS', 'unflag_21CM_54m_11202014_S0_T0_MS', 'unflag_21CM_54m_11202015_S0_T0_MS']
INFO:STIMELA:Remaining jobs : ['unflag_92CM_96m_11201064_S0_T0_MS', 'unflag_92CM_96m_11201065_S0_T0_MS', 'unflag_92CM_96m_11201065_S0_T1_MS', 'unflag_92CM_96m_11201065_S0_T10_MS', 'unflag_92CM_96m_11201065_S0_T11_MS', 'unflag_92CM_96m_11201065_S0_T12_MS', 'unflag_92CM_96m_11201065_S0_T13_MS', 'unflag_92CM_96m_11201065_S0_T14_MS', 'unflag_92CM_96m_11201065_S0_T2_MS', 'unflag_92CM_96m_11201065_S0_T3_MS', 'unflag_92CM_96m_11201065_S0_T4_MS', 'unflag_92CM_96m_11201065_S0_T5_MS', 'unflag_92CM_96m_11201065_S0_T6_MS', 'unflag_92CM_96m_11201065_S0_T7_MS', 'unflag_92CM_96m_11201065_S0_T8_MS', 'unflag_92CM_96m_11201065_S0_T9_MS', 'unflag_92CM_96m_11201066_S0_T0_MS', 'unflag_92CM_96m_11201067_S0_T0_MS', 'unflag_21CM_54m_11202011_S0_T0_MS', 'unflag_21CM_54m_11202012_S0_T0_MS', 'unflag_21CM_54m_11202013_S0_T0_MS', 'unflag_21CM_54m_11202013_S0_T1_MS', 'unflag_21CM_54m_11202013_S0_T2_MS', 'unflag_21CM_54m_11202014_S0_T0_MS', 'unflag_21CM_54m_11202015_S0_T0_MS']
2017-08-10 10:58:15,745 - STIMELA - INFO - Logging remaining task: unflag_92CM_96m_11201064_S0_T0_MS
INFO:STIMELA:Logging remaining task: unflag_92CM_96m_11201064_S0_T0_MS
2017-08-10 10:58:15,746 - STIMELA - INFO - Logging remaining task: unflag_92CM_96m_11201065_S0_T0_MS
INFO:STIMELA:Logging remaining task: unflag_92CM_96m_11201065_S0_T0_MS
2017-08-10 10:58:15,746 - STIMELA - INFO - Logging remaining task: unflag_92CM_96m_11201065_S0_T1_MS
INFO:STIMELA:Logging remaining task: unflag_92CM_96m_11201065_S0_T1_MS
2017-08-10 10:58:15,746 - STIMELA - INFO - Logging remaining task: unflag_92CM_96m_11201065_S0_T10_MS
INFO:STIMELA:Logging remaining task: unflag_92CM_96m_11201065_S0_T10_MS
2017-08-10 10:58:15,747 - STIMELA - INFO - Logging remaining task: unflag_92CM_96m_11201065_S0_T11_MS
INFO:STIMELA:Logging remaining task: unflag_92CM_96m_11201065_S0_T11_MS
2017-08-10 10:58:15,747 - STIMELA - INFO - Logging remaining task: unflag_92CM_96m_11201065_S0_T12_MS
INFO:STIMELA:Logging remaining task: unflag_92CM_96m_11201065_S0_T12_MS
2017-08-10 10:58:15,747 - STIMELA - INFO - Logging remaining task: unflag_92CM_96m_11201065_S0_T13_MS
INFO:STIMELA:Logging remaining task: unflag_92CM_96m_11201065_S0_T13_MS
2017-08-10 10:58:15,748 - STIMELA - INFO - Logging remaining task: unflag_92CM_96m_11201065_S0_T14_MS
INFO:STIMELA:Logging remaining task: unflag_92CM_96m_11201065_S0_T14_MS
2017-08-10 10:58:15,748 - STIMELA - INFO - Logging remaining task: unflag_92CM_96m_11201065_S0_T2_MS
INFO:STIMELA:Logging remaining task: unflag_92CM_96m_11201065_S0_T2_MS
2017-08-10 10:58:15,748 - STIMELA - INFO - Logging remaining task: unflag_92CM_96m_11201065_S0_T3_MS
INFO:STIMELA:Logging remaining task: unflag_92CM_96m_11201065_S0_T3_MS
2017-08-10 10:58:15,749 - STIMELA - INFO - Logging remaining task: unflag_92CM_96m_11201065_S0_T4_MS
INFO:STIMELA:Logging remaining task: unflag_92CM_96m_11201065_S0_T4_MS
2017-08-10 10:58:15,749 - STIMELA - INFO - Logging remaining task: unflag_92CM_96m_11201065_S0_T5_MS
INFO:STIMELA:Logging remaining task: unflag_92CM_96m_11201065_S0_T5_MS
2017-08-10 10:58:15,749 - STIMELA - INFO - Logging remaining task: unflag_92CM_96m_11201065_S0_T6_MS
INFO:STIMELA:Logging remaining task: unflag_92CM_96m_11201065_S0_T6_MS
2017-08-10 10:58:15,750 - STIMELA - INFO - Logging remaining task: unflag_92CM_96m_11201065_S0_T7_MS
INFO:STIMELA:Logging remaining task: unflag_92CM_96m_11201065_S0_T7_MS
2017-08-10 10:58:15,750 - STIMELA - INFO - Logging remaining task: unflag_92CM_96m_11201065_S0_T8_MS
INFO:STIMELA:Logging remaining task: unflag_92CM_96m_11201065_S0_T8_MS
2017-08-10 10:58:15,750 - STIMELA - INFO - Logging remaining task: unflag_92CM_96m_11201065_S0_T9_MS
INFO:STIMELA:Logging remaining task: unflag_92CM_96m_11201065_S0_T9_MS
2017-08-10 10:58:15,751 - STIMELA - INFO - Logging remaining task: unflag_92CM_96m_11201066_S0_T0_MS
INFO:STIMELA:Logging remaining task: unflag_92CM_96m_11201066_S0_T0_MS
2017-08-10 10:58:15,751 - STIMELA - INFO - Logging remaining task: unflag_92CM_96m_11201067_S0_T0_MS
INFO:STIMELA:Logging remaining task: unflag_92CM_96m_11201067_S0_T0_MS
2017-08-10 10:58:15,751 - STIMELA - INFO - Logging remaining task: unflag_21CM_54m_11202011_S0_T0_MS
INFO:STIMELA:Logging remaining task: unflag_21CM_54m_11202011_S0_T0_MS
2017-08-10 10:58:15,752 - STIMELA - INFO - Logging remaining task: unflag_21CM_54m_11202012_S0_T0_MS
INFO:STIMELA:Logging remaining task: unflag_21CM_54m_11202012_S0_T0_MS
2017-08-10 10:58:15,752 - STIMELA - INFO - Logging remaining task: unflag_21CM_54m_11202013_S0_T0_MS
INFO:STIMELA:Logging remaining task: unflag_21CM_54m_11202013_S0_T0_MS
2017-08-10 10:58:15,752 - STIMELA - INFO - Logging remaining task: unflag_21CM_54m_11202013_S0_T1_MS
INFO:STIMELA:Logging remaining task: unflag_21CM_54m_11202013_S0_T1_MS
2017-08-10 10:58:15,753 - STIMELA - INFO - Logging remaining task: unflag_21CM_54m_11202013_S0_T2_MS
INFO:STIMELA:Logging remaining task: unflag_21CM_54m_11202013_S0_T2_MS
2017-08-10 10:58:15,753 - STIMELA - INFO - Logging remaining task: unflag_21CM_54m_11202014_S0_T0_MS
INFO:STIMELA:Logging remaining task: unflag_21CM_54m_11202014_S0_T0_MS
2017-08-10 10:58:15,753 - STIMELA - INFO - Logging remaining task: unflag_21CM_54m_11202015_S0_T0_MS
INFO:STIMELA:Logging remaining task: unflag_21CM_54m_11202015_S0_T0_MS
2017-08-10 10:58:15,754 - STIMELA - INFO - Saving pipeline information in .last_reduce_abel_781.json
INFO:STIMELA:Saving pipeline information in .last_reduce_abel_781.json
2017-08-10 10:58:15,852 - STIMELA - INFO - Container unflag_92CM_96m_11201063_S0_T0_MS-140584951238472150236267965 has been stopped.
INFO:STIMELA:Container unflag_92CM_96m_11201063_S0_T0_MS-140584951238472150236267965 has been stopped.
running: docker rm unflag_92CM_96m_11201063_S0_T0_MS-140584951238472150236267965
unflag_92CM_96m_11201063_S0_T0_MS-140584951238472150236267965
Traceback (most recent call last):
  File "/data/bhugo/stimela/bin/stimela", line 13, in <module>
    stimela.main([a for a in sys.argv[1:]])
  File "/data/bhugo/stimela/local/lib/python2.7/site-packages/stimela/__init__.py", line 608, in main
    _cmd(argv)
  File "/data/bhugo/stimela/local/lib/python2.7/site-packages/stimela/__init__.py", line 304, in run
    execfile(args.script, _globals)
  File "a781_reduce.py", line 162, in <module>
    recipe.run()
  File "/data/bhugo/stimela/local/lib/python2.7/site-packages/stimela/recipe.py", line 459, in run
    job.run_docker_job()
  File "/data/bhugo/stimela/local/lib/python2.7/site-packages/stimela/recipe.py", line 74, in run_docker_job
    self.job.start()
  File "/data/bhugo/stimela/local/lib/python2.7/site-packages/stimela/docker.py", line 159, in start
    utils.xrun("docker", ["start", "-a", self.name])
  File "/data/bhugo/stimela/local/lib/python2.7/site-packages/stimela/utils/__init__.py", line 72, in xrun
    raise SystemError('%s: returns errr code %d'%(command, process.returncode))
stimela.recipe.PipelineException: Exception occurred while running pipeline component 'unflag_92CM_96m_11201063_S0_T0_MS': docker: returns errr code 1
                     
```

**Comment by bennahugo** [comment]
Okay this one (w)is a docker bug. Going to close it but maybe should put a minimum version requirement in the readme
