### ISSUE TITLE
HDF5 support is not compiled into this casacore version

### ISSUE THREAD

**Issue by Athanaseus** [SpheMakh/Stimela#168]
2017-08-07 08:10:21,604 - STIMELA - INFO - STEP 3 :: image_lwimager:: Image data
INFO:STIMELA:STEP 3 :: image_lwimager:: Image data
INFO:root:Validating parameters...       CAB = lwimager
INFO:root:Parameters validated and saved. Parameter file is: stimela_parameter_files/image_lwimager-139971202531824150209334822.json
2017-08-07 08:10:21,606 - STIMELA - INFO - Instantiating container [image_lwimager-139971202531824150209334822]. The container ID is printed below.
2017-08-07 08:10:21,606 - STIMELA - INFO - Instantiating container [image_lwimager-139971202531824150209334822]. The container ID is printed below.
INFO:STIMELA:Instantiating container [image_lwimager-139971202531824150209334822]. The container ID is printed below.
running: docker create --user 1005  -v /home/ramaila/gitPackages/Stimela/stimela:/utils:ro -v /data/ramaila/new/busy/source_properties/stimela_parameter_files:/configs:ro -v /etc/group:/etc/group:ro -v /etc/passwd:/etc/passwd:ro -v /etc/shadow:/etc/shadow:ro -v /etc/sudoers.d:/etc/sudoers.d:ro -v /data/ramaila/new/busy/source_properties/msdir:/home/ramaila/msdir:rw -v /data/ramaila/new/busy/source_properties/input:/input:ro -v /data/ramaila/new/busy/source_properties/output:/home/ramaila/output:rw  -e CONFIG=/configs/image_lwimager-139971202531824150209334822.json -e MSDIR=/home/ramaila/msdir -e INPUT=/input -e OUTPUT=/home/ramaila/output -e LOGFILE=/home/ramaila/output/log-image_lwimager.txt  --name image_lwimager-139971202531824150209334822 --shm-size 1gb ramaila_cab/lwimager 
dffc6d168c263f53a82c2c9c73e18927d9fc5b0131552e7fbdd77c56402a6417
running: docker start -a image_lwimager-139971202531824150209334822
lwimager: Version 1.4.0
2017-08-07 08:10:22	INFO	Imager::open() 	Opening MeasurementSet /home/ramaila/msdir/meerkat_noise.ms
2017-08-07 08:10:25	INFO	imager::data selection	Selecting data
2017-08-07 08:10:26	INFO	imager::data selection	Selected all 725760 visibilities
2017-08-07 08:10:26	INFO	Imager::selectDataChannel() 	Selecting channel 0 for spw 0
2017-08-07 08:10:26	INFO	imager::defineimage()	Defining image properties:nx=1024 ny=1024 cellx='2arcsec' celly='2arcsec' stokes=I' mode=channel nchan=1 start=0 step=1 spwids=[0] fieldid=0 facets=1 frame=1 distance='0m'
2017-08-07 08:10:26	INFO	imager::defineimage()	 phaseCenter='field-0 ' mStart='Radialvelocity: 0' qStep='1 km/s'' mFreqStart='Frequency: 0
2017-08-07 08:10:26	INFO	imager::weight()	Weighting MS: Imaging weights will be changed
2017-08-07 08:10:26	INFO	imager::weight()	Briggs weighting: sidelobes will be suppressed over full image
2017-08-07 08:10:27	INFO	VisSetUtil::VisImagingWeight() 	Normal robustness, robust = -2
2017-08-07 08:10:27	INFO	imager::setoptions() 	Setting processing options
2017-08-07 08:10:27	INFO	imager::makeimage() 	Calculating image (without full skyequation)
2017-08-07 08:10:27	INFO	imager::makeimage() 	Making dirty image from corrected data 
2017-08-07 08:10:27	INFO	imager::makeimage() 	Image is : /home/ramaila/output/noise_image.dirty.img
2017-08-07 08:10:27	INFO	imager::createFTMachine() 	Performing interferometric gridding...
HDF5 error: HDF5 support is not compiled into this casacore version
running: lwimager weight=briggs image=/home/ramaila/output/noise_image.dirty.img fillmodel=True chanstep=1 threshold=0 operation=image img_chanstart=0 field=0 img_nchan=1 stokes=I wprojplanes=0 gain=0.1 cachesize=512 robust=-2.0 data=CORRECTED_DATA niter=0 img_chanstep=1 nchan=1 chanstart=0 hdf5=False npix=1024 cellsize=2.0arcsec chanmode=channel mode=channel ms=/home/ramaila/msdir/meerkat_noise.ms fixed=False
Traceback (most recent call last):
  File "/code/run.py", line 190, in <module>
    _run(prefix, **options)
  File "/code/run.py", line 51, in _run
    utils.xrun(cab['binary'], args)
  File "/utils/utils/__init__.py", line 72, in xrun
    raise SystemError('%s: returns errr code %d'%(command, process.returncode))
SystemError: lwimager: returns errr code 1
2017-08-07 08:10:30,561 - STIMELA - INFO - Recipe execution failed while running job image_lwimager
2017-08-07 08:10:30,561 - STIMELA - INFO - Recipe execution failed while running job image_lwimager
INFO:STIMELA:Recipe execution failed while running job image_lwimager

**Comment by Athanaseus** [comment]
PR #169
