### ISSUE TITLE
add montage 

### ISSUE THREAD

**Issue by SpheMakh** [SpheMakh/Stimela#176]
http://www.astropy.org/montage-wrapper/

**Comment by SpheMakh** [comment]
Do this now!

**Comment by Fil8** [comment]
I installed montage and wrote the following recipe:

```
        mosaic_outdir = pipeline.output+'/masking/mosaic/'
	recipe.add('cab/montage', key,
		   {
			 "input_dir"            : '/masking/formosaic/'+":output",
			 #"output_dir"            : '/masking/mosaic/'+":output",
			 "exact_size"        	: True,
	           },
		   input=pipeline.input,
		   output=mosaic_outdir,
		   label="Make Mosaic")	
```
but it looks like the output directory is not defined: 

```
running: docker create --user 1001:1001  -v /home/maccagni/programs/meerkathi-venv/local/lib/python2.7/site-packages/stimela:/utils:ro -v /home/maccagni/FornaxA/MeerKAT/fa2/stimela_parameter_files:/configs:ro -v /home/maccagni/FornaxA/MeerKAT/fa2/msdir_fa2:/home/maccagni/msdir:rw -v /home/maccagni/FornaxA/MeerKAT/fa2/input:/input:ro -v /home/maccagni/FornaxA/MeerKAT/fa2/output/masking/mosaic:/home/maccagni/output:rw  -e CONFIG=/configs/make_mosaic-139693269355856152629375533.json -e MSDIR=/home/maccagni/msdir -e INPUT=/input -e HOME=/home/maccagni/output -e OUTPUT=/home/maccagni/output -e LOGFILE=/home/maccagni/output/log-make_mosaic.txt  --name make_mosaic-139693269355856152629375533 --shm-size 1gb maccagni_cab/montage 
c975578816851b34d7cc9be05c1c29756939e8195a4a7b16e69ba5a7bd52111d
running: docker start -a make_mosaic-139693269355856152629375533
Traceback (most recent call last):
  File "/code/run.py", line 23, in <module>
    args["output_dir"] = OUTPUT
NameError: name 'OUTPUT' is not defined
```

if instead I add a keyword ```output_dir``` , this is not included in the cabs/montage parameters: 

```
  File "/home/maccagni/programs/meerkathi-venv/local/lib/python2.7/site-packages/stimela/cargo/cab/__init__.py", line 279, in update
    raise RuntimeError("Parameter {0} is unknown. Run 'stimela cabs -i {1}' to get help on this cab".format(name, self.task))
PipelineException: Exception occurred while running pipeline component 'Make Mosaic': Parameter output_dir is unknown. Run 'stimela cabs -i montage.mosiac' to get help on this cab

```

**Comment by SpheMakh** [comment]
Fixed in 4eafc2f. Please update and try again

**Comment by Fil8** [comment]
The montage mosaic creates a /mosaic/ folder with inside a file mosaic.fits. 

This output folder cannot be the output of Stimela, because Stimela creates a log file in that folder before running Montage. So if Stimela does this then Montage crashes. Is it possible to tell montage the output directory with a keyword ```output_dirs```?


```
recipe = stimela.Recipe("montage", ms_dir=MSDIR)

step = '2'

recipe.add('cab/montage', step,
        {
        input_dir: 'fields/formosaic' #in INPUT folder
        },
        input=INPUT,
        output=OUTPUT)

recipe.run()
```

so something like this does not work.

**Comment by SpheMakh** [comment]
I see. Would it be okay to create output_dir in the stimela output folder?

**Comment by Fil8** [comment]
Yes I think it would work. It is a bit out of date, but I still need this fix.

**Comment by SpheMakh** [comment]
Fixed
