### ISSUE TITLE
Loaded json is none

### ISSUE THREAD

**Issue by bennahugo** [SpheMakh/Stimela#188]
Still tracking this one down... looks like an invalid parameters file is being passed to the json reader
```
ERROR:meerkathi:Traceback (most recent call last):
  File "/var/lib/jenkins/workspace/IC5264/12/projects/pyenv/local/lib/python2.7/site-packages/meerkathi/__init__.py", line 183, in main
    pipeline.run_workers()
  File "/var/lib/jenkins/workspace/IC5264/12/projects/pyenv/local/lib/python2.7/site-packages/meerkathi/__init__.py", line 125, in run_workers
    build_label=self.stimela_build)
  File "/var/lib/jenkins/workspace/IC5264/12/projects/pyenv/local/lib/python2.7/site-packages/stimela/recipe.py", line 279, in __init__
    self.proc_logger = utils.logger.StimelaLogger(stimela.LOG_FILE)
  File "/var/lib/jenkins/workspace/IC5264/12/projects/pyenv/local/lib/python2.7/site-packages/stimela/utils/logger.py", line 25, in __init__
    if self.info.get(item, None) is None:
AttributeError: 'NoneType' object has no attribute 'get'
```

**Comment by bennahugo** [comment]
Think this one was having multiple stimela versions with stale files in ~/.stimela. Closing
