### ISSUE TITLE
tigger-convert diagnostic plots error

### ISSUE THREAD

**Issue by KshitijT** [SpheMakh/Stimela#191]
tigger_convert throws an error when dignostic plots are requested.
Stimela code is : 
```
recipe.add('cab/tigger_convert', 'dignostic_plots',{
     "input-skymodel" : calmodel,
     "output-skymodel" : 'test.lsm.html:output',
     "primary-beam" : beam,
     "fits-l-axis" : 'X',
     "fits-m-axis" : 'Y',
     "pa-from-ms"  : ['grid_beamrot_4MHz_20chan_grid6.ms'],
     "enable-plots" : True,
},
     input=INPUT,
     output=OUTPUT,
     label='dignostic_plots:: Plot dignostic plots')
```
Error is:
```
Traceback (most recent call last):
  File "/usr/local/bin/tigger-convert", line 713, in <module>
    bg = pbexp(r,fq);
NameError: name 'pbexp' is not defined
running: tigger-convert --append-type auto --primary-beam '/input/fits/scaled_to_avg_JVLA-L_interp_by_wt_ant5-$(xy)_$(reim).fits' --fits-l-axis X --fits-m-axis Y --enable-plots  --pa-from-ms /home/kshitij/msdir/grid_beamrot_4MHz_20chan_grid6.ms:0 /input/sky_grid_dom_source_calmodel6.txt /home/kshitij/output/test.lsm.html
Traceback (most recent call last):
  File "/code/run.py", line 53, in <module>
    utils.xrun(cab['binary'], args + [inlsm, outlsm])
  File "/utils/utils/__init__.py", line 72, in xrun
    raise SystemError('%s: returns errr code %d'%(command, process.returncode))

```

Not sure if this issue belongs in Stimela or in /ska-sa/tigger.

**Comment by SpheMakh** [comment]
@KshitijT this is tigger-issue
