### ISSUE TITLE
Wsclean "threads" parameter not matching.

### ISSUE THREAD

**Issue by KshitijT** [SpheMakh/Stimela#192]
Setting the "threads" parameter for wsclean gives the following error:
```
+ An exception occured:
+ >>> Unknown parameter: threads
+ + + + + + + + + + + + + + + + + + +
running: /usr/bin/wsclean -name /home/kshitij/output/Cyg_A_COMB-s5.1 -threads 8 -mem 100 -weight briggs -0.5 -superweight 1.0 -weighting-rank-filter-size 16 -size 6000 6000 -trim 4000 4000 -scale 0.06arcsec -channelsout 16 -nosmallinversion -gridmode kb -gkernelsize 7 -oversampling 63 -pol I -intervalsout 1 -datacolumn CORRECTED_DATA -niter 2000000 -auto-threshold 0.25 -auto-mask 5 -gain 0.1 -mgain 0.85 -joinchannels -multiscale -multiscale-scale-bias 0.6 -fit-spectral-pol 4 -deconvolution-channels 8 -fitbeam -ellipticalbeam /home/kshitij/msdir/S-CYG-A-3.5-10S-4M-split.MS/ /home/kshitij/msdir/S-CYG-B-3.5-10S-4M-split.MS/ /home/kshitij/msdir/S-CYG-C-3.5-10S-4M-split.MS/
Traceback (most recent call last):
  File "/code/run.py", line 54, in <module>
    utils.xrun(cab['binary'], args + [mslist])
  File "/utils/utils/__init__.py", line 72, in xrun
    raise SystemError('%s: returns errr code %d'%(command, process.returncode))
SystemError: /usr/bin/wsclean: returns errr code 255

```

Swapping "threads" to "j" in the parameters.json file gives the correct result.

**Comment by SpheMakh** [comment]
Fixed in branch release-0.3.1
