### ISSUE TITLE
Error running simms in stimela

### ISSUE THREAD

**Issue by kelahard** [SpheMakh/Stimela#211]
I got this error while simulating MS with _simms_ in _stimela_:
`Unable to find image 'iheanetu_cab/simms:latest' locally
Error response from daemon: repository iheanetu_cab/simms not found: does not exist or no pull access`, _see details below_. All the efforts to resolve this was unsuccessful. What could be the problem?

`...
2017-11-17 17:20:53,999 - STIMELA - INFO - Running job simms
INFO:STIMELA:Running job simms
2017-11-17 17:20:53,999 - STIMELA - INFO - STEP 1 :: simms:: Make empty MS
INFO:STIMELA:STEP 1 :: simms:: Make empty MS
INFO:root:Validating parameters...       CAB = simms
INFO:root:Parameters validated and saved. Parameter file is: stimela_parameter_files/simms-140142126950800151093205017.json
2017-11-17 17:20:54,043 - STIMELA - INFO - Instantiating container [simms-140142126950800151093205017]. The container ID is printed below.
INFO:STIMELA:Instantiating container [simms-140142126950800151093205017]. The container ID is printed below.
running: docker create --user 1093  -v /home/iheanetu/kela/local/lib/python2.7/site-packages/stimela:/utils:ro -v /net/tina/home/iheanetu/calibrations/calibration_reduction_sim/stimela_parameter_files:/configs:ro -v /etc/group:/etc/group:ro -v /etc/passwd:/etc/passwd:ro -v /etc/shadow:/etc/shadow:ro -v /etc/sudoers.d:/etc/sudoers.d:ro -v /net/tina/home/iheanetu/calibrations/calibration_reduction_sim/msdir:/home/iheanetu/msdir:rw -v /net/tina/home/iheanetu/calibrations/calibration_reduction_sim/input_dir:/input:ro -v /net/tina/home/iheanetu/calibrations/calibration_reduction_sim/output_rand24_35_gsolu1:/home/iheanetu/output:rw  -e CONFIG=/configs/simms-140142126950800151093205017.json -e MSDIR=/home/iheanetu/msdir -e INPUT=/input -e OUTPUT=/home/iheanetu/output -e LOGFILE=/home/iheanetu/output/log-simms.txt  --name simms-140142126950800151093205017 --shm-size 1gb iheanetu_cab/simms 
Unable to find image 'iheanetu_cab/simms:latest' locally
Error response from daemon: repository iheanetu_cab/simms not found: does not exist or no pull access
2017-11-17 17:20:59,514 - STIMELA - INFO - Recipe execution failed while running job simms
INFO:STIMELA:Recipe execution failed while running job simms
2017-11-17 17:20:59,515 - STIMELA - INFO - Completed jobs : []
INFO:STIMELA:Completed jobs : []
2017-11-17 17:20:59,515 - STIMELA - INFO - Remaining jobs : []
INFO:STIMELA:Remaining jobs : []
2017-11-17 17:20:59,515 - STIMELA - INFO - Saving pipeline information in .last_beam_rotation_test.json
INFO:STIMELA:Saving pipeline information in .last_beam_rotation_test.json
Traceback (most recent call last):
  File "/home/iheanetu/kela/bin/stimela", line 13, in <module>
    stimela.main([a for a in sys.argv[1:]])
  File "/home/iheanetu/kela/local/lib/python2.7/site-packages/stimela/__init__.py", line 608, in main
    _cmd(argv)
  File "/home/iheanetu/kela/local/lib/python2.7/site-packages/stimela/__init__.py", line 304, in run
    execfile(args.script, _globals)
  File "simulation_ripple_3c147_23.py", line 377, in <module>
    loopcalibration(gsolu_freq=gs_freq,numbchans=110,skynumb=25,skysub_numb=iskysub_numb,folder_numb=foldernum)
  File "simulation_ripple_3c147_23.py", line 345, in loopcalibration
    ], resume=False)
  File "/home/iheanetu/kela/local/lib/python2.7/site-packages/stimela/recipe.py", line 459, in run
    job.run_docker_job()
  File "/home/iheanetu/kela/local/lib/python2.7/site-packages/stimela/recipe.py", line 72, in run_docker_job
    self.job.create(*['--user {}'.format(UID)])
  File "/home/iheanetu/kela/local/lib/python2.7/site-packages/stimela/docker.py", line 122, in create
    self.COMMAND or ""])
  File "/home/iheanetu/kela/local/lib/python2.7/site-packages/stimela/utils/__init__.py", line 72, in xrun
    raise SystemError('%s: returns errr code %d'%(command, process.returncode))
stimela.recipe.PipelineException: Exception occurred while running pipeline component 'simms:: Make empty MS': docker create: returns errr code 1`

**Comment by kelahard** [comment]
I am running my script on _**elwood**_ sever.

**Comment by Athanaseus** [comment]
Try the following commands if not done so already after installing stimela, might be that the docker images are not locally accessible.
`stimela pull`
and 
`stimela build`

**Comment by kelahard** [comment]
So, every time the machine restarts one should `pull` and `build`?

**Comment by bennahugo** [comment]
No it could be that @gijzelaerr cleaned out the images. Just pull and rebuild as @Athanaseus said

**Comment by gijzelaerr** [comment]
yep, i cleaned the images since it was quite a mess of old images and I assumed you can easily reconstruct or download an image.

**Comment by bennahugo** [comment]
Yea it is trivial to recreate a version - wastes an hour but not an issue

**Comment by bennahugo** [comment]
Thanks for cleaning the box @gijzelaerr
