### ISSUE TITLE
Error running simsky in stimela - on elwood

### ISSUE THREAD

**Issue by kelahard** [SpheMakh/Stimela#219]
I got these errors while simulating visibilies with simsky in stimela:

```-----------------------------------
Stimela version     : 0.3.0
Cab name            : iheanetu_cab/simulator
-------------------------------------
/usr/lib/python2.7/dist-packages/matplotlib/font_manager.py:273: UserWarning: Matplotlib is building the font cache using fc-list. This may take a moment.
  warnings.warn('Matplotlib is building the font cache using fc-list. This may take a moment.')
### Starting meqserver
### Attaching to configuration file /code/tdlconf.profiles
### Loading config section sim
### Setting option ms_sel.input_column=DATA
### Setting option ms_sel.field_index=0
### Setting option ms_sel.msname=/home/iheanetu/msdir/random1_600.ms
### Setting option me.sky.tiggerskymodel=1
### Setting option me.p_enable=1
### Setting option me.e_enable=1
### Setting option pybeams_fits.m_axis=Y
### Setting option me.use_smearing=0
### Setting option sim_mode=sim only
### Setting option me.e_all_stations=1
### Setting option pybeams_fits.filename_pattern=/input/fits/scaled_JVLA-L_interp_by_wt_ant5-$(xy)_$(reim).fits
### Setting option me.e_module=Siamese_OMS_pybeams_fits
### Setting option noise_stddev=0.0273861278753
### Setting option pybeams_fits.sky_rotation=1
### Setting option ms_sel.ddid_index=0
### Setting option pybeams_fits.l_axis=X
### Setting option tiggerlsm.filename=/input/skymodel600.txt
### Setting option ms_sel.output_column=DATA
### Compiling /usr/local/lib/python2.7/dist-packages/Cattery/Siamese/turbo-sim.py
### (using previously set options)
  (Meow.MSUtils: found /usr/bin/lwimager, can use it for imaging.)
  (Meow.MSUtils: found image viewer /usr/local/bin/tigger)
Successful readonly open of autonoread-locked table /home/iheanetu/msdir/random1_600.ms: 24 columns, 84240 rows
Successful readonly open of autonoread-locked table /home/iheanetu/msdir/random1_600.ms/ANTENNA: 8 columns, 27 rows
Successful readonly open of default-locked table /home/iheanetu/msdir/random1_600.ms/OBSERVATION: 9 columns, 1 rows
Successful readonly open of autonoread-locked table /home/iheanetu/msdir/random1_600.ms/POLARIZATION: 4 columns, 1 rows
Successful readonly open of autonoread-locked table /home/iheanetu/msdir/random1_600.ms/DATA_DESCRIPTION: 3 columns, 1 rows
Successful readonly open of autonoread-locked table /home/iheanetu/msdir/random1_600.ms/SPECTRAL_WINDOW: 14 columns, 1 rows
Successful readonly open of autonoread-locked table /home/iheanetu/msdir/random1_600.ms/FIELD: 9 columns, 1 rows
Using LSM module from Tigger (1.3.8) 1.3.8 at /usr/local/lib/python2.7/dist-packages/Tigger (in path)
Successful readonly open of default-locked table /home/iheanetu/msdir/random1_600.ms: 24 columns, 84240 rows
Successful readonly open of default-locked table /home/iheanetu/msdir/random1_600.ms: 24 columns, 84240 rows
Successful readonly open of default-locked table /home/iheanetu/msdir/random1_600.ms: 24 columns, 84240 rows
Successful readonly open of default-locked table /home/iheanetu/msdir/random1_600.ms: 24 columns, 84240 rows
Loading /input/skymodel600.txt: ASCII table
###  TDL script successfully compiled. 2903 node definitions
  (of which 2 are root nodes) sent to meqserver.
### Running TDL job "_simulate_MS"
3.8Gb vb(InterpolatedBeams.py:511:init_voltage_beams): loading beam files /input/fits/scaled_JVLA-L_interp_by_wt_ant5-rr_re.fits /input/fits/scaled_JVLA-L_interp_by_wt_ant5-rr_im.fits
11.5Gb vb(InterpolatedBeams.py:511:init_voltage_beams): loading beam files /input/fits/scaled_JVLA-L_interp_by_wt_ant5-rl_re.fits /input/fits/scaled_JVLA-L_interp_by_wt_ant5-rl_im.fits
19.3Gb vb(InterpolatedBeams.py:511:init_voltage_beams): loading beam files /input/fits/scaled_JVLA-L_interp_by_wt_ant5-lr_re.fits /input/fits/scaled_JVLA-L_interp_by_wt_ant5-lr_im.fits
27.1Gb vb(InterpolatedBeams.py:511:init_voltage_beams): loading beam files /input/fits/scaled_JVLA-L_interp_by_wt_ant5-ll_re.fits /input/fits/scaled_JVLA-L_interp_by_wt_ant5-ll_im.fits
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/Cattery/Siamese/OMS/InterpolatedBeams.py", line 587, in get_result
    beam = vb.interpolate(freqaxis=self._freqaxis,**grid);
  File "/usr/local/lib/python2.7/dist-packages/Cattery/Siamese/OMS/InterpolatedBeams.py", line 335, in interpolate
    scale if numpy.isscalar(scale) else scale[above|below])
IndexError: boolean index did not match indexed array along dimension 0; dimension is 32 but corresponding boolean dimension is 4
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/Cattery/Siamese/OMS/InterpolatedBeams.py", line 587, in get_result
    beam = vb.interpolate(freqaxis=self._freqaxis,**grid);
  File "/usr/local/lib/python2.7/dist-packages/Cattery/Siamese/OMS/InterpolatedBeams.py", line 335, in interpolate
    scale if numpy.isscalar(scale) else scale[above|below])
..............................
..............................
..............................
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/Cattery/Siamese/OMS/InterpolatedBeams.py", line 587, in get_result
    beam = vb.interpolate(freqaxis=self._freqaxis,**grid);
  File "/usr/local/lib/python2.7/dist-packages/Cattery/Siamese/OMS/InterpolatedBeams.py", line 335, in interpolate
    scale if numpy.isscalar(scale) else scale[above|below])
IndexError: boolean index did not match indexed array along dimension 0; dimension is 32 but corresponding boolean dimension is 4
Traceback (most recent call last):
  File "/usr/bin/meqtree-pipeliner.py", line 176, in <module>
    res = func(mqs,None,wait=True);
  File "/usr/local/lib/python2.7/dist-packages/Cattery/Siamese/turbo-sim.py", line 235, in _simulate_MS
    mqs.execute('VisDataMux',mssel.create_io_request(),wait=wait);
  File "/usr/lib/python2.7/dist-packages/Timba/Apps/meqserver.py", line 173, in execute
    return self.meq('Node.Execute',rec,wait=wait);
  File "/usr/lib/python2.7/dist-packages/Timba/Apps/meqserver.py", line 126, in meq
    msg = self.await(replyname,resume=True,timeout=wait);
  File "/usr/lib/python2.7/dist-packages/Timba/Apps/multiapp_proxy.py", line 525, in await
    res = self._pwp.await(self._rcv_prefix + what,timeout=await_timeout,resume=resume);
  File "/usr/lib/python2.7/dist-packages/Timba/octopussy.py", line 434, in await
    self.resume_events();
  File "/usr/lib/python2.7/dist-packages/Timba/octopussy.py", line 414, in resume_events
    self._lock.release();
  File "/usr/lib/python2.7/threading.py", line 204, in release
    raise RuntimeError("cannot release un-acquired lock")
RuntimeError: cannot release un-acquired lock```

I've run:
```stimela pull
stimela build```

But the problem still persisted so I executed:

```pip install -U git+https://github.com/SpheMakh/Stimela
stimela build -i casa_plotms
stimela clean -ac
stimela pull
stimela build```

But the errors persisted.

Please, does anyone know what I can do to resolve these errors?

**Comment by bennahugo** [comment]
@kelahard This looks like a meqtrees/cattery bug not a stimela issue - can you report the issue on ska-sa/cattery? Are you sure the measurement set has the correct frequency axis for the beams you are trying to use, that your beams don't contain nans and all your sources fall within the beam area? I've seen similar strangeness if the things fall outside the valid interpolation domain.

**Comment by kelahard** [comment]
Thanks @bennahugo.
I'm re-running an old script with a beam cube that has 1024 beams (from frequency between 1.008GHz and 2.031GHz - having a frequency resolution of 1MHz) using the same input parameters as before. And the beams also doesn't have nans but I'll still take it up with the meqtrees/cattery issues.

**Comment by o-smirnov** [comment]
Yeah this is definitely a ``meqtrees-cattery`` issue. Please open a report there, and provide links to your MS, scripts and .tdl.conf.
