### ISSUE TITLE
run.sh does not have correct execution permissions

### ISSUE THREAD

**Issue by bennahugo** [SpheMakh/Stimela#277]
@Sebokolodi is reporting the following issue after rebuilding CASA cabs to include the latest ephemeris, using the fix described in #276 

![image](https://user-images.githubusercontent.com/7934586/43123406-57a52072-8f24-11e8-9951-37a4922dc4bc.png)

It appears that the casa run.sh wrapping script that is included in the cab docker images does not have correct permissions set.

The steps to reproduce is to check out master
Purge previous installations and remove ~/.stimela
Install master in developer mode
Update the CASA base docker file to include #276 
docker build -t stimela/casa:1.0.0 
stimela build

@Sebokolodi can you run chmod -R a+rx on the shell file in question and see if it solves the issue.

**Comment by bennahugo** [comment]
I will try and reproduce this issue with a fresh installation

**Comment by bennahugo** [comment]
Cannot reproduce this issue @Sebokolodi. Although I've found that the latest setjy has another bug (this time its a CASA 5 bug). I would recommend going back to 4.7
Building casa 5 with updated ephemeris:
```
Sending build context to Docker daemon  2.048kB
Step 1/7 : FROM stimela/casa:0.3.2
 ---> 4a0ddd29f44c
Step 2/7 : RUN docker-apt-install git locales
 ---> Using cache
 ---> 177bdd2a189f
Step 3/7 : RUN locale-gen en_US.UTF-8
 ---> Using cache
 ---> b82740097245
Step 4/7 : RUN pip install -U pip
 ---> Using cache
 ---> ff6d94a816c7
Step 5/7 : RUN pip install -U drive-casa pyyaml
 ---> Using cache
 ---> cfc0ac1fba39
Step 6/7 : RUN pip install -U git+https://github.com/SpheMakh/crasa.git
 ---> Using cache
 ---> 618bf3c78949
Step 7/7 : RUN casa-config --exec update-data
 ---> Using cache
 ---> 401512eb5370
Successfully built 401512eb5370
Successfully tagged stimela/casa:1.0.0
```
building fixvis (computes uv coordinates and will moan if the UTC offset table is out of date):
```
stimela build -uo casa_fixvis                                                                                                                                   
running: docker build --force-rm -f /tmp/tmpIST0fQ/tmpOyGC1f -t bhugo_cab/casa_fixvis /tmp/tmpIST0fQ
Sending build context to Docker daemon  8.192kB
Step 1/8 : FROM stimela/casa:1.0.0
 ---> 401512eb5370
Step 2/8 : MAINTAINER <sphemakh@gmail.com>
 ---> Running in fcaa78f52a49
Removing intermediate container fcaa78f52a49
 ---> da80ea97931b
Step 3/8 : ADD src /code
 ---> 5e8fa65d40a4
Step 4/8 : ENV LOGFILE ${OUTPUT}/logfile.txt
 ---> Running in 47e4a0811b9d
Removing intermediate container 47e4a0811b9d
 ---> fdfacceced19
Step 5/8 : WORKDIR /home/bhugo/output/
Removing intermediate container d5f5a14eebdc
 ---> 5b83d186d89b
Step 6/8 : RUN useradd -r -u 1000 -U bhugo
 ---> Running in e492b7c67aa7
Removing intermediate container e492b7c67aa7
 ---> 29e6da50da25
Step 7/8 : USER bhugo
 ---> Running in f3523199053c
Removing intermediate container f3523199053c
 ---> d4fef31ac986
Step 8/8 : CMD /code/run.sh
 ---> Running in 0368981d3506
Removing intermediate container 0368981d3506
 ---> 3836c9ceeaa8
Successfully built 3836c9ceeaa8
Successfully tagged bhugo_cab/casa_fixvis:latest
```

Running fixvis gives no SEVERE errors:
```
running: docker start -a test-139798845219480153242908631

=========================================
The start-up time of CASA may vary
depending on whether the shared libraries
are cached or not.
=========================================

IPython 5.1.0 -- An enhanced Interactive Python.

CASA 5.1.2-4   -- Common Astronomy Software Applications

2018-07-24 10:44:49     INFO    ::casa  CASA Version 5.1.2-4  
2018-07-24 10:44:52     INFO    fixvis::::
2018-07-24 10:44:52     INFO    fixvis::::+     ##########################################
2018-07-24 10:44:52     INFO    fixvis::::+     ##### Begin Task: fixvis             #####
2018-07-24 10:44:52     INFO    fixvis::::      fixvis(vis="/home/bhugo/msdir/1491291289.1ghz.1.1ghz.4hrs.ms",outputvis="/home/bhugo/msdir/1491291289.1ghz.1.1ghz.4hrs.ms",field="",refcode="",reuse=False,
2018-07-24 10:44:52     INFO    fixvis::::+             phasecenter="",distances="",datacolumn="all")
2018-07-24 10:44:52     INFO    fixvis::::      Will overwrite original MS ...
2018-07-24 10:44:52     INFO    fixvis::::      Will leave phase centers unchanged.
2018-07-24 10:44:52     INFO    fixvis::::      Recalculating the UVW coordinates ...
2018-07-24 10:44:52     INFO    Imager::open()  Opening MeasurementSet /home/bhugo/msdir/1491291289.1ghz.1.1ghz.4hrs.ms
2018-07-24 10:44:52     INFO    SubMS::parseColumnNames()       Using DATA MODEL_DATA CORRECTED_DATA columns.
2018-07-24 10:44:52     INFO    FixVis::setFields       Selecting fields 0 1 2 
2018-07-24 10:44:52     INFO    MSUVWGenerator::make_uvws       Rows handled: 0/190920
2018-07-24 10:44:53     INFO    fixvis::::      CASA Version 5.1.2-4  
2018-07-24 10:44:53     INFO    fixvis::::
2018-07-24 10:44:54     INFO    fixvis::::      ##### End Task: fixvis               #####
2018-07-24 10:44:54     INFO    fixvis::::+     ##########################################
2018-07-24 12:44:57,494 - STIMELA - INFO - Container [test-139798845219480153242908631] has executed successfully
INFO:STIMELA:Container [test-139798845219480153242908631] has executed successfully
2018-07-24 12:44:57,494 - STIMELA - INFO - Runtime was 0:00:10.849623.
INFO:STIMELA:Runtime was 0:00:10.849623.
2018-07-24 12:44:57,503 - STIMELA - INFO - Container test-139798845219480153242908631 has been stopped.
INFO:STIMELA:Container test-139798845219480153242908631 has been stopped.
running: docker rm test-139798845219480153242908631
test-139798845219480153242908631
2018-07-24 12:44:57,630 - STIMELA - INFO - Saving pipeline information in .last_test_listobs.json
INFO:STIMELA:Saving pipeline information in .last_test_listobs.json
2018-07-24 12:44:57,630 - STIMELA - INFO - Recipe executed successfully
INFO:STIMELA:Recipe executed successfully
```

whereas prior to the fix it would crash:
```
(venv_stimela)> $ stimela run stimela_casa.test.py                                                                                                                                
2018-07-24 11:43:26,120 - STIMELA - INFO - ---------------------------------
2018-07-24 11:43:26,120 - STIMELA - INFO - Stimela version 1.0.0
2018-07-24 11:43:26,120 - STIMELA - INFO - Sphesihle Makhathini <sphemakh@gmail.com>
2018-07-24 11:43:26,120 - STIMELA - INFO - Running: test listobs
2018-07-24 11:43:26,120 - STIMELA - INFO - ---------------------------------
2018-07-24 11:43:26,131 - STIMELA - INFO - Adding cab 'bhugo_cab/casa_fixvis' to recipe. The container will be named 'test'
INFO:STIMELA:Adding cab 'bhugo_cab/casa_fixvis' to recipe. The container will be named 'test'
2018-07-24 11:43:26,131 - STIMELA - INFO - Running job test
INFO:STIMELA:Running job test
2018-07-24 11:43:26,131 - STIMELA - INFO - STEP 1 :: testlobs
INFO:STIMELA:STEP 1 :: testlobs
INFO:root:Validating parameters...       CAB = casa_fixvis
INFO:root:Parameters validated and saved. Parameter file is: stimela_parameter_files/test-140463776764568153242540612.json
2018-07-24 11:43:26,131 - STIMELA - INFO - Instantiating container [test-140463776764568153242540612]. The container ID is printed below.
INFO:STIMELA:Instantiating container [test-140463776764568153242540612]. The container ID is printed below.
running: docker create --user 1000:1000  -v /home/bhugo/workspace/Stimela/stimela:/utils:ro -v /home/bhugo/workspace/stimela_parameter_files:/configs:ro -v /home/bhugo/workspace/msdir:/home/bhugo/msdir:rw -v /home/bhugo/workspace/input:/input:ro -v /home/bhugo/workspace/output:/home/bhugo/output:rw  -e CONFIG=/configs/test-140463776764568153242540612.json -e MSDIR=/home/bhugo/msdir -e INPUT=/input -e HOME=/home/bhugo/output -e OUTPUT=/home/bhugo/output -e LOGFILE=/home/bhugo/output/log-test.txt  --name test-140463776764568153242540612 --shm-size 1gb bhugo_cab/casa_fixvis 
870dc3a99c28305a564a7875f8a7596bfd1805eccba1f54b1696e0305c54b815
running: docker start -a test-140463776764568153242540612

=========================================
The start-up time of CASA may vary
depending on whether the shared libraries
are cached or not.
=========================================

IPython 5.1.0 -- An enhanced Interactive Python.

CASA 5.1.2-4   -- Common Astronomy Software Applications

2018-07-24 09:43:28     INFO    ::casa  CASA Version 5.1.2-4  
2018-07-24 09:43:30     INFO    fixvis::::
2018-07-24 09:43:30     INFO    fixvis::::+     ##########################################
2018-07-24 09:43:30     INFO    fixvis::::+     ##### Begin Task: fixvis             #####
2018-07-24 09:43:30     INFO    fixvis::::      fixvis(vis="/home/bhugo/msdir/1491291289.1ghz.1.1ghz.4hrs.ms",outputvis="/home/bhugo/msdir/1491291289.1ghz.1.1ghz.4hrs.ms",field="",refcode="",reuse=False,
2018-07-24 09:43:30     INFO    fixvis::::+             phasecenter="",distances="",datacolumn="all")
2018-07-24 09:43:30     INFO    fixvis::::      Will overwrite original MS ...
2018-07-24 09:43:30     INFO    fixvis::::      Will leave phase centers unchanged.
2018-07-24 09:43:30     INFO    fixvis::::      Recalculating the UVW coordinates ...
2018-07-24 09:43:30     INFO    Imager::open()  Opening MeasurementSet /home/bhugo/msdir/1491291289.1ghz.1.1ghz.4hrs.ms
2018-07-24 09:43:30     INFO    SubMS::parseColumnNames()       Using DATA MODEL_DATA CORRECTED_DATA columns.
2018-07-24 09:43:30     INFO    FixVis::setFields       Selecting fields 0 1 2 
2018-07-24 09:43:30     INFO    MSUVWGenerator::make_uvws       Rows handled: 0/190920
2018-07-24 09:43:30     SEVERE  MeasTable::dUTC(Double) (file ../../measures/Measures/MeasTable.cc, line 4396)  Leap second table TAI_UTC seems out-of-date. 
2018-07-24 09:43:30     SEVERE  MeasTable::dUTC(Double) (file ../../measures/Measures/MeasTable.cc, line 4396)+ Until the table is updated (see the CASA documentation or your system admin),
2018-07-24 09:43:30     SEVERE  MeasTable::dUTC(Double) (file ../../measures/Measures/MeasTable.cc, line 4396)+ times and coordinates derived from UTC could be wrong by 1s or more.
2018-07-24 09:43:32     INFO    fixvis::::      CASA Version 5.1.2-4  
2018-07-24 09:43:32     INFO    fixvis::::
2018-07-24 09:43:33     INFO    fixvis::::      ##### End Task: fixvis               #####
2018-07-24 09:43:33     INFO    fixvis::::+     ##########################################
Traceback (most recent call last):
  File "/code/run.py", line 27, in <module>
    task.run()
  File "/usr/local/lib/python2.7/dist-packages/Crasa/Crasa.py", line 97, in run
    raise CasaException("CASA failed while running task {0:s}".format(self.task))
Crasa.Crasa.CasaException: CASA failed while running task fixvis
2018-07-24 11:43:35,700 - STIMELA - INFO - Recipe execution failed while running job test
INFO:STIMELA:Recipe execution failed while running job test
2018-07-24 11:43:35,700 - STIMELA - INFO - Completed jobs : []
INFO:STIMELA:Completed jobs : []
2018-07-24 11:43:35,700 - STIMELA - INFO - Remaining jobs : []
INFO:STIMELA:Remaining jobs : []
2018-07-24 11:43:35,700 - STIMELA - INFO - Saving pipeline information in .last_test_listobs.json
INFO:STIMELA:Saving pipeline information in .last_test_listobs.json
2018-07-24 11:43:35,713 - STIMELA - INFO - Container test-140463776764568153242540612 has been stopped.
INFO:STIMELA:Container test-140463776764568153242540612 has been stopped.
running: docker rm test-140463776764568153242540612
test-140463776764568153242540612
Traceback (most recent call last):
  File "/home/bhugo/workspace/venv_stimela/bin/stimela", line 10, in <module>
    execfile(__file__)
  File "/home/bhugo/workspace/Stimela/bin/stimela", line 13, in <module>
    stimela.main([a for a in sys.argv[1:]])
  File "/home/bhugo/workspace/Stimela/stimela/__init__.py", line 615, in main
    _cmd(argv)
  File "/home/bhugo/workspace/Stimela/stimela/__init__.py", line 311, in run
    execfile(args.script, _globals)
  File "stimela_casa.test.py", line 12, in <module>
    recipe.run()
  File "/home/bhugo/workspace/Stimela/stimela/recipe.py", line 464, in run
    job.run_docker_job()
  File "/home/bhugo/workspace/Stimela/stimela/recipe.py", line 80, in run_docker_job
    self.job.start()
  File "/home/bhugo/workspace/Stimela/stimela/docker.py", line 159, in start
    utils.xrun("docker", ["start", "-a", self.name])
  File "/home/bhugo/workspace/Stimela/stimela/utils/__init__.py", line 74, in xrun
    raise SystemError('%s: returns errr code %d'%(command, process.returncode))
stimela.recipe.PipelineException: Exception occurred while running pipeline component 'testlobs': docker: returns errr code 1
```

**Comment by bennahugo** [comment]
Perhaps @SpheMakh has an idea what can be the cause for this

**Comment by SpheMakh** [comment]
I assume this was fixed. Reopen otherwise
