### ISSUE TITLE
task error codes no longer checked

### ISSUE THREAD

**Issue by bennahugo** [SpheMakh/Stimela#317]
```
meerkathi - 2019-01-12 22:03:05,037 INFO - 2019-01-12 20:03:02	INFO	Calibrater::solve	The following calibration terms are arranged for apply:
meerkathi - 2019-01-12 22:03:05,044 INFO - 2019-01-12 20:03:02	INFO	Calibrater::solve	.   B Jones: table=/home/benjamin/output/meerkathi-1491291289-1gc1.B0 select= interp=linear,linear spwmap=[-1] calWt=true
meerkathi - 2019-01-12 22:03:05,051 INFO - 2019-01-12 20:03:02	INFO	Calibrater::solve	.   K Jones: table=/home/benjamin/output/meerkathi-1491291289-1gc1.K0 select= interp=linear spwmap=[-1] calWt=false
meerkathi - 2019-01-12 22:03:05,058 INFO - 2019-01-12 20:03:02	INFO	Calibrater::solve	The following calibration term is arranged for solve:
meerkathi - 2019-01-12 22:03:05,064 INFO - 2019-01-12 20:03:02	INFO	Calibrater::solve	.   G Jones: table=/home/benjamin/output/meerkathi-1491291289-1gc1.G0 append=true solint=inf refantmode='flex' refant='m000' minsnr=3 apmode=AP solnorm=false
meerkathi - 2019-01-12 22:03:05,071 INFO - 2019-01-12 20:03:02	INFO	ChannelAverageTVI::parseConfiguration	Channel bin is [-1]
meerkathi - 2019-01-12 22:03:05,077 INFO - 2019-01-12 20:03:02	INFO	Calibrater::solve	For solint = inf, found 55 solution intervals.
meerkathi - 2019-01-12 22:03:05,084 INFO - 2019-01-12 20:03:02	SEVERE	Calibrater::solve	Caught exception: Table DataManager error: Invalid operation: TSM: no array in row 4523 of column MODEL_DATA in /home/benjamin/msdir/1491291289.ms/table.f25
meerkathi - 2019-01-12 22:03:05,091 INFO - 2019-01-12 20:03:02	INFO	Calibrater::solve	Reseting entire solve/apply state.
meerkathi - 2019-01-12 22:03:05,099 INFO - 2019-01-12 20:03:02	SEVERE		Exception Reported: Error in Calibrater::solve.
meerkathi - 2019-01-12 22:03:05,106 INFO - *** Error *** Error in Calibrater::solve.
meerkathi - 2019-01-12 22:03:05,112 INFO - 2019-01-12 20:03:02	SEVERE	gaincal::::	Error in gaincal: Error in Calibrater::solve.
meerkathi - 2019-01-12 22:03:05,119 INFO - 2019-01-12 20:03:02	SEVERE	gaincal::::	An error occurred running task gaincal.
meerkathi - 2019-01-12 22:03:05,125 INFO - Traceback (most recent call last):
meerkathi - 2019-01-12 22:03:05,132 INFO -   File "/scratch/code/run.py", line 27, in <module>
meerkathi - 2019-01-12 22:03:05,138 INFO -     task.run()
meerkathi - 2019-01-12 22:03:05,145 INFO -   File "/usr/local/lib/python2.7/dist-packages/Crasa/Crasa.py", line 97, in run
meerkathi - 2019-01-12 22:03:05,152 INFO -     raise CasaException("CASA failed while running task {0:s}".format(self.task))
meerkathi - 2019-01-12 22:03:05,158 INFO - Crasa.Crasa.CasaException: CASA failed while running task gaincal
meerkathi - 2019-01-12 22:03:05,165 CRITICAL - INFO:STIMELA-40:Container [gain_cal_gain_0-14060418890585615473232965] has executed successfully
meerkathi - 2019-01-12 22:03:05,171 CRITICAL - INFO:STIMELA-40:Runtime was 0:00:09.134396.
meerkathi - 2019-01-12 22:03:05,209 CRITICAL - INFO:STIMELA-40:Container gain_cal_gain_0-14060418890585615473232965 has been stopped.
meerkathi - 2019-01-12 22:03:05,247 INFO - running: docker rm gain_cal_gain_0-14060418890585615473232965
meerkathi - 2019-01-12 22:03:05,371 INFO - gain_cal_gain_0-14060418890585615473232965
meerkathi - 2019-01-12 22:03:05,380 CRITICAL - INFO:STIMELA-40:Running job plot_gain_cal_0
meerkathi - 2019-01-12 22:03:05,387 CRITICAL - INFO:STIMELA-40:STEP 9 :: plot_gain_cal_0:: Plot gaincal phase ms=1491291289.ms
meerkathi - 2019-01-12 22:03:05,393 CRITICAL - INFO:root:Validating parameters...       CAB = ragavi
```
and
```
meerkathi - 2019-01-12 22:03:19,008 INFO - 2019-01-12 20:03:15	INFO	fluxscale::::+	##########################################
meerkathi - 2019-01-12 22:03:19,014 INFO - 2019-01-12 20:03:15	INFO	fluxscale::::+	##### Begin Task: fluxscale          #####
meerkathi - 2019-01-12 22:03:19,019 INFO - 2019-01-12 20:03:15	INFO	fluxscale::::	fluxscale(vis="/home/benjamin/msdir/1491291289.ms",caltable="/home/benjamin/output/meerkathi-1491291289-1gc1.G0",fluxtable="/home/benjamin/output/meerkathi-1491291289-1gc1.F0",reference=['0408-65'],transfer=['0252-712'],
meerkathi - 2019-01-12 22:03:19,026 INFO - 2019-01-12 20:03:15	INFO	fluxscale::::+	        listfile="",append=False,refspwmap=[-1],gainthreshold=-1.0,antenna="",
meerkathi - 2019-01-12 22:03:19,033 INFO - 2019-01-12 20:03:15	INFO	fluxscale::::+	        timerange="",scan="",incremental=False,fitorder=1,display=False)
meerkathi - 2019-01-12 22:03:19,039 INFO - 2019-01-12 20:03:15	INFO	fluxscale::calibrater::open	****Using NEW VI2-driven calibrater tool****
meerkathi - 2019-01-12 22:03:19,045 INFO - 2019-01-12 20:03:15	INFO	fluxscale::calibrater::open	Opening MS: /home/benjamin/msdir/1491291289.ms for calibration.
meerkathi - 2019-01-12 22:03:19,051 INFO - 2019-01-12 20:03:15	INFO	fluxscale::Calibrater::	Initializing nominal selection to the whole MS.
meerkathi - 2019-01-12 22:03:19,057 INFO - 2019-01-12 20:03:15	INFO	fluxscale::calibrater::fluxscale	Beginning fluxscale--(MSSelection version)-------
meerkathi - 2019-01-12 22:03:19,063 INFO - 2019-01-12 20:03:16	SEVERE	fluxscale::Calibrater::fluxscale	Caught Exception:  Cannot find solutions for transfer field(s)
meerkathi - 2019-01-12 22:03:19,069 INFO - 2019-01-12 20:03:16	SEVERE	fluxscale::::	Exception Reported: Error in Calibrater::fluxscale.
meerkathi - 2019-01-12 22:03:19,075 INFO - *** Error *** Error in Calibrater::fluxscale.
meerkathi - 2019-01-12 22:03:19,080 INFO - 2019-01-12 20:03:16	SEVERE	fluxscale::::	An error occurred running task fluxscale.
meerkathi - 2019-01-12 22:03:19,085 INFO - Traceback (most recent call last):
meerkathi - 2019-01-12 22:03:19,089 INFO -   File "/scratch/code/run.py", line 27, in <module>
meerkathi - 2019-01-12 22:03:19,094 INFO -     task.run()
meerkathi - 2019-01-12 22:03:19,098 INFO -   File "/usr/local/lib/python2.7/dist-packages/Crasa/Crasa.py", line 97, in run
meerkathi - 2019-01-12 22:03:19,103 INFO -     raise CasaException("CASA failed while running task {0:s}".format(self.task))
meerkathi - 2019-01-12 22:03:19,108 INFO - Crasa.Crasa.CasaException: CASA failed while running task fluxscale
meerkathi - 2019-01-12 22:03:19,113 CRITICAL - INFO:STIMELA-40:Container [transfer_fluxscale_0-140604189226576154732329686] has executed successfully
meerkathi - 2019-01-12 22:03:19,119 CRITICAL - INFO:STIMELA-40:Runtime was 0:00:09.408991.
meerkathi - 2019-01-12 22:03:19,157 CRITICAL - INFO:STIMELA-40:Container transfer_fluxscale_0-140604189226576154732329686 has been stopped.
```

**Comment by bennahugo** [comment]
There is more:
```
meerkathi - 2019-01-12 22:09:51,347 CRITICAL - INFO:STIMELA-90:---------------------------------
meerkathi - 2019-01-12 22:09:51,355 CRITICAL - INFO:STIMELA-90:Stimela version 1.0.0
meerkathi - 2019-01-12 22:09:51,362 CRITICAL - INFO:STIMELA-90:Sphesihle Makhathini <sphemakh@gmail.com>
meerkathi - 2019-01-12 22:09:51,370 CRITICAL - INFO:STIMELA-90:Running: Self calibration loop
meerkathi - 2019-01-12 22:09:51,377 CRITICAL - INFO:STIMELA-90:---------------------------------
meerkathi - 2019-01-12 22:09:51,587 CRITICAL - INFO:STIMELA-90:Adding cab 'benjamin_cab/wsclean' to recipe. The container will be named 'image_1'
meerkathi - 2019-01-12 22:09:51,777 CRITICAL - INFO:STIMELA-90:Adding cab 'benjamin_cab/sofia' to recipe. The container will be named 'make_sofia_mask'
meerkathi - 2019-01-12 22:09:51,898 CRITICAL - INFO:STIMELA-90:Adding cab 'benjamin_cab/aimfast' to recipe. The container will be named 'aimfast'
meerkathi - 2019-01-12 22:09:51,904 CRITICAL - INFO:STIMELA-90:Running job image_1
meerkathi - 2019-01-12 22:09:51,909 CRITICAL - INFO:STIMELA-90:STEP 1 :: image_1:: Make image after first round of calibration
meerkathi - 2019-01-12 22:09:51,915 CRITICAL - INFO:root:Validating parameters...       CAB = wsclean
meerkathi - 2019-01-12 22:09:51,922 CRITICAL - INFO:root:Parameters validated and saved. Parameter file is: stimela_parameter_files/image_1-14060418871464015473237915.json
meerkathi - 2019-01-12 22:09:51,928 CRITICAL - INFO:STIMELA-90:Instantiating container [image_1-14060418871464015473237915]. The container ID is printed below.
meerkathi - 2019-01-12 22:09:51,933 INFO - running: docker create --user 1000:1000  -v /home/benjamin/workspace/stimela/stimela:/scratch/stimela:ro -v /home/benjamin/workspace/stimela_parameter_files:/configs:ro -v /home/benjamin/workspace/msdir:/home/benjamin/msdir:rw -v /home/benjamin/workspace/input:/input:ro -v /home/benjamin/workspace/output:/home/benjamin/output:rw  -e CONFIG=/configs/image_1-14060418871464015473237915.json -e MSDIR=/home/benjamin/msdir -e INPUT=/input -e HOME=/home/benjamin/output -e OUTPUT=/home/benjamin/output -e LOGFILE=/home/benjamin/output/log-image_1.txt  --name image_1-14060418871464015473237915 --shm-size 1gb benjamin_cab/wsclean
meerkathi - 2019-01-12 22:09:52,592 INFO - 8048110bb454233844d05320c66a79f06f1e78f3e094f7dd884c4c708f07b44d
meerkathi - 2019-01-12 22:09:52,696 INFO - running: docker start -a image_1-14060418871464015473237915
meerkathi - 2019-01-12 22:09:54,929 INFO - running: wsclean -name /home/benjamin/output/meerkathi-pipeline_1 -mem 100 -weight briggs -1.5 -super-weight 1.0 -weighting-rank-filter-size 16 -size 5540 5540 -scale 1.3asec -channels-out 3 -grid-mode kb -kernel-size 7 -oversampling 63 -pol I -intervals-out 1 -data-column DATA -niter 1000000 -auto-threshold 0.5 -auto-mask 40 -gain 0.1 -mgain 0.9 -join-channels -multiscale-scale-bias 0.6 -multiscale-scales 0,40,80,150 -fit-spectral-pol 1 -fit-beam -elliptical-beam -padding 1.3 /home/benjamin/msdir/1491291289-corr.ms
meerkathi - 2019-01-12 22:09:54,936 INFO - Illegal instruction (core dumped)
meerkathi - 2019-01-12 22:09:54,942 INFO - Traceback (most recent call last):
meerkathi - 2019-01-12 22:09:54,947 INFO -   File "/scratch/code/run.py", line 92, in <module>
meerkathi - 2019-01-12 22:09:54,952 INFO -     utils.xrun(cab['binary'], args + [mslist])
meerkathi - 2019-01-12 22:09:54,957 INFO -   File "/scratch/stimela/utils/__init__.py", line 73, in xrun
meerkathi - 2019-01-12 22:09:54,962 INFO -     raise SystemError('%s: returns errr code %d'%(command, process.returncode))
meerkathi - 2019-01-12 22:09:54,968 INFO - SystemError: wsclean: returns errr code 132
meerkathi - 2019-01-12 22:09:54,973 CRITICAL - INFO:STIMELA-90:Container [image_1-14060418871464015473237915] has executed successfully
meerkathi - 2019-01-12 22:09:54,978 CRITICAL - INFO:STIMELA-90:Runtime was 0:00:02.369868.
meerkathi - 2019-01-12 22:09:55,016 CRITICAL - INFO:STIMELA-90:Container image_1-14060418871464015473237915 has been stopped.
meerkathi - 2019-01-12 22:09:55,056 INFO - running: docker rm image_1-14060418871464015473237915
```

**Comment by bennahugo** [comment]
and more
```
meerkathi - 2019-01-12 22:03:55,316 INFO - |___|    |_______||_______||___|   |___|  |_______||___|   |___|  |__| |__||___| |_||__| |__|  |___|
meerkathi - 2019-01-12 22:03:55,322 INFO - 
meerkathi - 2019-01-12 22:03:55,328 INFO - ------------------------------------------------------------------------------------------------------
meerkathi - 2019-01-12 22:03:55,334 INFO - 
meerkathi - 2019-01-12 22:03:55,339 INFO - politsiyakat - INFO 2019-01-12 20:03:54,265:	Module installed at '/usr/local/lib/python2.7/dist-packages/politsiyakat' version 0.3.8
meerkathi - 2019-01-12 22:03:55,344 INFO - politsiyakat - INFO 2019-01-12 20:03:54,267:	Running task 'flag_phase_drifts' with the following arguments:
meerkathi - 2019-01-12 22:03:55,350 INFO - politsiyakat - INFO 2019-01-12 20:03:54,267:		plot_size:6
meerkathi - 2019-01-12 22:03:55,355 INFO - politsiyakat - INFO 2019-01-12 20:03:54,267:		nrows_chunk:5000
meerkathi - 2019-01-12 22:03:55,360 INFO - politsiyakat - INFO 2019-01-12 20:03:54,267:		data_column:CORRECTED_DATA
meerkathi - 2019-01-12 22:03:55,365 INFO - politsiyakat - INFO 2019-01-12 20:03:54,267:		field:0,1,2
meerkathi - 2019-01-12 22:03:55,370 INFO - politsiyakat - INFO 2019-01-12 20:03:54,267:		cal_field:0,1
meerkathi - 2019-01-12 22:03:55,374 INFO - politsiyakat - INFO 2019-01-12 20:03:54,267:		baseline_to_group_threshold:10
meerkathi - 2019-01-12 22:03:55,379 INFO - politsiyakat - INFO 2019-01-12 20:03:54,267:		scan_to_scan_threshold:10
meerkathi - 2019-01-12 22:03:55,385 INFO - politsiyakat - INFO 2019-01-12 20:03:54,267:		output_dir:./
meerkathi - 2019-01-12 22:03:55,389 INFO - politsiyakat - INFO 2019-01-12 20:03:54,267:		simulate:False
meerkathi - 2019-01-12 22:03:55,394 INFO - politsiyakat - INFO 2019-01-12 20:03:54,267:		msname:/home/benjamin/msdir/1491291289.ms
meerkathi - 2019-01-12 22:03:55,399 INFO - politsiyakat - INFO 2019-01-12 20:03:54,267:		dpi:300
meerkathi - 2019-01-12 22:03:55,404 INFO - politsiyakat - INFO 2019-01-12 20:03:54,280:	/home/benjamin/msdir/1491291289.ms appears to be a valid measurement set with 190920 rows
meerkathi - 2019-01-12 22:03:55,409 INFO - politsiyakat - WARNING 2019-01-12 20:03:54,281:	Warning: defaulting to plot dpi of 300. Keyword 'plot_dpi' can be used to control this behaviour.
meerkathi - 2019-01-12 22:03:55,415 INFO - politsiyakat - INFO 2019-01-12 20:03:54,281:	Will process the following fields:
meerkathi - 2019-01-12 22:03:55,421 INFO - politsiyakat - INFO 2019-01-12 20:03:54,281:		(0): 0408-65 (calibrator)
meerkathi - 2019-01-12 22:03:55,426 INFO - politsiyakat - INFO 2019-01-12 20:03:54,281:		(1): 0252-712 (calibrator)
meerkathi - 2019-01-12 22:03:55,431 INFO - politsiyakat - INFO 2019-01-12 20:03:54,281:		(2): DEEP_2
meerkathi - 2019-01-12 22:03:55,436 INFO - politsiyakat - INFO 2019-01-12 20:03:54,293:	/home/benjamin/msdir/1491291289.ms appears to be a valid measurement set with 190920 rows
meerkathi - 2019-01-12 22:03:55,441 INFO - politsiyakat - INFO 2019-01-12 20:03:54,326:	Waiting for remaining jobs to finish...
meerkathi - 2019-01-12 22:03:55,446 INFO - Traceback (most recent call last):
meerkathi - 2019-01-12 22:03:55,452 INFO -   File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
meerkathi - 2019-01-12 22:03:55,457 INFO -     "__main__", fname, loader, pkg_name)
meerkathi - 2019-01-12 22:03:55,462 INFO -   File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
meerkathi - 2019-01-12 22:03:55,467 INFO -     exec code in run_globals
meerkathi - 2019-01-12 22:03:55,472 INFO -   File "/usr/local/lib/python2.7/dist-packages/politsiyakat/__main__.py", line 25, in <module>
meerkathi - 2019-01-12 22:03:55,477 INFO -     politsiyakat.main(sys.argv[1:])
meerkathi - 2019-01-12 22:03:55,482 INFO -   File "/usr/local/lib/python2.7/dist-packages/politsiyakat/__init__.py", line 129, in main
meerkathi - 2019-01-12 22:03:55,487 INFO -     run_func(**args.kwargs)
meerkathi - 2019-01-12 22:03:55,492 INFO -   File "/usr/local/lib/python2.7/dist-packages/politsiyakat/modules/flag_tasks.py", line 162, in flag_phase_drifts
meerkathi - 2019-01-12 22:03:55,497 INFO -     for chunk_i, data in enumerate(iter(dp)):
meerkathi - 2019-01-12 22:03:55,502 INFO -   File "/usr/local/lib/python2.7/dist-packages/politsiyakat/data/data_provider.py", line 210, in next
meerkathi - 2019-01-12 22:03:55,507 INFO -     self.__rows_read = self.__nxchunk_wkr.result()
meerkathi - 2019-01-12 22:03:55,512 INFO -   File "/usr/local/lib/python2.7/dist-packages/concurrent/futures/_base.py", line 462, in result
meerkathi - 2019-01-12 22:03:55,517 INFO -     return self.__get_result()
meerkathi - 2019-01-12 22:03:55,522 INFO -   File "/usr/local/lib/python2.7/dist-packages/concurrent/futures/thread.py", line 63, in run
meerkathi - 2019-01-12 22:03:55,527 INFO -     result = self.fn(*self.args, **self.kwargs)
meerkathi - 2019-01-12 22:03:55,532 INFO -   File "/usr/local/lib/python2.7/dist-packages/politsiyakat/data/data_provider.py", line 340, in _read_buffer
meerkathi - 2019-01-12 22:03:55,537 INFO -     nrows_to_read)
meerkathi - 2019-01-12 22:03:55,542 INFO -   File "/usr/lib/python2.7/dist-packages/casacore/tables/table.py", line 1024, in getcolnp
meerkathi - 2019-01-12 22:03:55,546 INFO -     return self._getcolvh(columnname, startrow, nrow, rowincr, nparray)
meerkathi - 2019-01-12 22:03:55,551 INFO - RuntimeError: Table DataManager error: Invalid operation: TSM: no array in row 0 of column CORRECTED_DATA in /home/benjamin/msdir/1491291289.ms/table.f26
meerkathi - 2019-01-12 22:03:55,556 INFO - Traceback (most recent call last):
meerkathi - 2019-01-12 22:03:55,561 INFO -   File "/scratch/code/run.py", line 32, in <module>
meerkathi - 2019-01-12 22:03:55,566 INFO -     utils.xrun(cab['binary'], ARGS)
meerkathi - 2019-01-12 22:03:55,570 INFO -   File "/scratch/stimela/utils/__init__.py", line 73, in xrun
meerkathi - 2019-01-12 22:03:55,575 INFO -     raise SystemError('%s: returns errr code %d'%(command, process.returncode))
meerkathi - 2019-01-12 22:03:55,580 INFO - SystemError: python -m politsiyakat: returns errr code 1
meerkathi - 2019-01-12 22:03:55,585 CRITICAL - INFO:STIMELA-40:Container [autoflag_closure_error_0-140604190123952154732329757] has executed successfully
meerkathi - 2019-01-12 22:03:55,590 CRITICAL - INFO:STIMELA-40:Runtime was 0:00:02.823662.
meerkathi - 2019-01-12 22:03:55,628 CRITICAL - INFO:STIMELA-40:Container autoflag_closure_error_0-14
```

**Comment by bennahugo** [comment]
yet on other  steps it works..
```
meerkathi - 2019-01-12 22:09:55,624 CRITICAL - INFO:STIMELA-90:Remaining jobs : ['aimfast']
meerkathi - 2019-01-12 22:09:55,630 CRITICAL - INFO:STIMELA-90:Logging remaining task: aimfast_1:: Image fidelity assessment for 1
meerkathi - 2019-01-12 22:09:55,636 CRITICAL - INFO:STIMELA-90:Saving pipeline information in .last_self_calibration_loop.json
meerkathi - 2019-01-12 22:09:55,643 ERROR - An unhandled exeption occured. If you think this is a bug please report it.
meerkathi - 2019-01-12 22:09:55,649 ERROR - Your logfile is here: /home/benjamin/workspace/meerkathi.log.
meerkathi - 2019-01-12 22:09:55,654 ERROR - You are running version: 0.1.0-527-g5072bf2
meerkathi - 2019-01-12 22:09:55,660 ERROR - Traceback (most recent call last):
  File "/home/benjamin/workspace/meerkathi/meerkathi/__init__.py", line 209, in __run
    pipeline.run_workers()
  File "/home/benjamin/workspace/meerkathi/meerkathi/workers/worker_administrator.py", line 156, in run_workers
    worker.worker(self, recipe, config)
  File "/home/benjamin/workspace/meerkathi/meerkathi/workers/self_cal_worker.py", line 990, in worker
    config, 'aimfast') else False):
  File "/home/benjamin/workspace/meerkathi/meerkathi/workers/self_cal_worker.py", line 811, in quality_check
    recipe.run()
  File "/home/benjamin/workspace/stimela/stimela/recipe.py", line 618, in run
    run_job()
  File "/home/benjamin/workspace/stimela/stimela/recipe.py", line 79, in run_docker_job
    self.job.parameter_file_name)
  File "/home/benjamin/workspace/stimela/stimela/cargo/cab/__init__.py", line 270, in update
    raise IOError("File '{0}' for parameter '{1}' could not be located at '{2}'.".format(_value, param.name, path))
PipelineException: Exception occurred while running pipeline component 'make_sofia_mask:: Make SoFiA mask': File 'meerkathi-pipeline_1-MFS-image.fits' for parameter 'import.inFile' could not be located at 'output/meerkathi-pipeline_1-MFS-image.fits'.

meerkathi - 2019-01-12 22:09:55,666 CRITICAL -   File "/home/benjamin/workspace/meerkathi/meerkathi/__init__.py", line 209, in __run
meerkathi - 2019-01-12 22:09:55,671 CRITICAL -     pipeline.run_workers()
meerkathi - 2019-01-12 22:09:55,676 CRITICAL -   File "/home/benjamin/workspace/meerkathi/meerkathi/workers/worker_administrator.py", line 156, in run_workers
meerkathi - 2019-01-12 22:09:55,681 CRITICAL -     worker.worker(self, recipe, config)
meerkathi - 2019-01-12 22:09:55,685 CRITICAL -   File "/home/benjamin/workspace/meerkathi/meerkathi/workers/self_cal_worker.py", line 990, in worker
meerkathi - 2019-01-12 22:09:55,691 CRITICAL -     config, 'aimfast') else False):
meerkathi - 2019-01-12 22:09:55,696 CRITICAL -   File "/home/benjamin/workspace/meerkathi/meerkathi/workers/self_cal_worker.py", line 811, in quality_check
meerkathi - 2019-01-12 22:09:55,701 CRITICAL -     recipe.run()
meerkathi - 2019-01-12 22:09:55,706 CRITICAL -   File "/home/benjamin/workspace/stimela/stimela/recipe.py", line 618, in run
meerkathi - 2019-01-12 22:09:55,711 CRITICAL -     run_job()
meerkathi - 2019-01-12 22:09:55,716 CRITICAL -   File "/home/benjamin/workspace/stimela/stimela/recipe.py", line 79, in run_docker_job
meerkathi - 2019-01-12 22:09:55,721 CRITICAL -     self.job.parameter_file_name)
meerkathi - 2019-01-12 22:09:55,726 CRITICAL -   File "/home/benjamin/workspace/stimela/stimela/cargo/cab/__init__.py", line 270, in update
meerkathi - 2019-01-12 22:09:55,732 CRITICAL -     raise IOError("File '{0}' for parameter '{1}' could not be located at '{2}'.".format(_value, param.name, path))
meerkathi - 2019-01-12 22:09:55,737 CRITICAL - PipelineException: Exception occurred while running pipeline component 'make_sofia_mask:: Make SoFiA mask': File 'meerkathi-pipeline_1-MFS-image.fits' for parameter 'import.inFile' could not be located at 'output/meerkathi-pipeline_1-MFS-image.fits'.
```
