### ISSUE TITLE
wsclean built mached to native instruction set

### ISSUE THREAD

**Issue by bennahugo** [SpheMakh/Stimela#318]
The wsclean included in stimela is not platform agnostic - you are building it marched to the instruction set
of the machine you were building it on @SpheMakh 

```
meerkathi - 2019-01-13 01:16:02,997 INFO - running: docker start -a image_1-139657143542096154733496162
meerkathi - 2019-01-13 01:16:05,353 INFO - running: wsclean -name /home/benjamin/output/meerkathi-pipeline_1 -mem 100 -weight briggs -1.5 -super-weight 1.0 -weighting-rank-filter-size 16 -size 5540 5540 -scale 1.3asec -channels-out 3 -grid-mode kb -kernel-size 7 -oversampling 63 -pol I -intervals-out 1 -data-column DATA -niter 1000000 -auto-threshold 0.5 -auto-mask 40 -gain 0.1 -mgain 0.9 -join-channels -multiscale-scale-bias 0.6 -multiscale-scales 0,40,80,150 -fit-spectral-pol 1 -fit-beam -elliptical-beam -padding 1.3 /home/benjamin/msdir/1491291289-corr.ms
meerkathi - 2019-01-13 01:16:05,362 INFO - Illegal instruction (core dumped)
meerkathi - 2019-01-13 01:16:05,369 INFO - Traceback (most recent call last):
meerkathi - 2019-01-13 01:16:05,376 INFO -   File "/scratch/code/run.py", line 92, in <module>
meerkathi - 2019-01-13 01:16:05,382 INFO -     utils.xrun(cab['binary'], args + [mslist])
meerkathi - 2019-01-13 01:16:05,388 INFO -   File "/scratch/stimela/utils/__init__.py", line 73, in xrun
meerkathi - 2019-01-13 01:16:05,394 INFO -     raise SystemError('%s: returns errr code %d'%(command, process.returncode))
```

**Comment by bennahugo** [comment]
The following needs to be set

```
cmake_minimum_required(VERSION 2.8.8)

project(wsclean)

include(CMakeVersionInfo.txt)

#if(NOT CMAKE_BUILD_TYPE)
#  set(CMAKE_BUILD_TYPE "Release")
#endif()

set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++11 -O3 -Wall -DNDEBUG")

if(PORTABLE)
  set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} ")
else()
  set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -march=native") 
endif(PORTABLE)
```
