### ISSUE TITLE
Aimfast cab description broken

### ISSUE THREAD

**Issue by bennahugo** [SpheMakh/Stimela#323]
@arwina raised this issue:
```
/home/jenkins/output/meerkathi-pipeline_1-MFS-image.fits --area-factor 10 --normality-model normaltest --label meerkathi_1
meerkathi - 2019-01-15 04:44:44,583 INFO - usage: aimfast [-h] [--tigger-model MODEL] [--restored-image RESTORED]
meerkathi - 2019-01-15 04:44:44,583 INFO -                [-psf PSF] [--residual-image RESIDUAL]
meerkathi - 2019-01-15 04:44:44,583 INFO -                [--normality-test TEST_NORMALITY] [-dr DATA_RANGE] [-af FACTOR]
meerkathi - 2019-01-15 04:44:44,583 INFO -                [--compare-models MODELS [MODELS ...]]
meerkathi - 2019-01-15 04:44:44,584 INFO -                [--compare-residuals NOISE [NOISE ...]] [-dp POINTS]
meerkathi - 2019-01-15 04:44:44,584 INFO -                [--label LABEL]
meerkathi - 2019-01-15 04:44:44,584 INFO - aimfast: error: unrecognized arguments: --normality-model normaltest
meerkathi - 2019-01-15 04:44:44,584 INFO - Traceback (most recent call last):
meerkathi - 2019-01-15 04:44:44,584 INFO -   File "/scratch/code/run.py", line 24, in <module>
meerkathi - 2019-01-15 04:44:44,584 INFO -     utils.xrun(cab['binary'], args)
meerkathi - 2019-01-15 04:44:44,584 INFO -   File "/scratch/stimela/utils/__init__.py", line 73, in xrun
meerkathi - 2019-01-15 04:44:44,584 INFO -     raise SystemError('%s: returns errr code %d'%(command, process.returncode))
meerkathi - 2019-01-15 04:44:44,585 INFO - SystemError: aimfast: returns errr code 2
meerkathi - 2019-01-15 04:44:44,585 CRITICAL - INFO:STIMELA-90:Container [aimfast-140007967573504154751994411] has executed successfully
meerkathi - 2019-01-15 04:44:44,585 CRITICAL - INFO:STIMELA-90:Runtime was 0:00:05.234494.
meerkathi - 2019-01-15 04:44:44,631 CRITICAL - INFO:STIMELA-90:Container aimfast-140007967573504154751994411 has been stopped.
meerkathi - 2019-01-15 04:44:44,671 INFO - running: docker rm aimfast-140007967573504154751994411
```
@Athanaseus please fix

**Comment by bennahugo** [comment]
Nevermind it was just a typo in the parameters file

**Comment by Athanaseus** [comment]
This is fixed.
