### ISSUE TITLE
Error running cleanmask (param type issue)

### ISSUE THREAD

**Issue by Athanaseus** [SpheMakh/Stimela#378]
```Running: docker start -a CleanMask-140585170930352155686979066
Running: cleanmask --image /home/athanaseus/output/meerkat_extended_SourceRecovery-masked-only_casa_clean-0000.image.fits --output /home/athanaseus/output/meerkat_extended_SourceRecovery-masked-only_casa_clean-0000.mask.fits --sigma 8.0 --boxes 11 --iters 3 --diter 20 --tolerance 0.05 --log-level INFO
usage: cleanmask [-h] [-i IMAGE] [-o OUTPUT] [-s SIGMA] [-it ITERS]
                 [-nb BOXES] [-ol OVERLAP] [-mv MASK_VALUE] [-d]
                 [-t TOLERANCE] [-di DITER] [-nn] [-pf PEAK_FRACTION]
                 [-ll {INFO,DEBUG,CRITICAL,WARNING}]
cleanmask: error: argument -s/--sigma: invalid int value: '8.0'

Traceback (most recent call last):
  File "/scratch/code/run.py", line 25, in <module>
    utils.xrun(cab["binary"], args)
  File "/scratch/stimela/utils/__init__.py", line 110, in xrun
    raise StimelaCabRuntimeError('%s: returns errr code %d' % (command, process.returncode))
utils.StimelaCabRuntimeError: cleanmask: returns errr code 2

2019-05-03 09:49:56,818 - STIMELA - INFO - Recipe execution failed while running job CleanMask
2019-05-03 09:49:56,819 - STIMELA - INFO - Completed jobs : []
2019-05-03 09:49:56,821 - STIMELA - INFO - Remaining jobs : []
2019-05-03 09:49:56,824 - STIMELA - INFO - Saving pipeline information in .last_make_pipeline.json
2019-05-03 09:49:56,856 - STIMELA - INFO - Container CleanMask-140585170930352155686979066 has been stopped.
Running: docker rm CleanMask-140585170930352155686979066
CleanMask-140585170930352155686979066```

**Comment by Athanaseus** [comment]
This is solved in the new release of `cleanmask`.
i.e. It now takes float.
