### ISSUE TITLE
Stimela build : udocker inspect return non-zero exit status

### ISSUE THREAD

**Issue by Popiette** [SpheMakh/Stimela#405]
I am trying to install stimela in a virtual environment on a debian based system.
When i run `stimela build` I get this error
```
(skavenv) ska@taurus-13:~$ stimela build
Running: docker build --force-rm -f /tmp/tmpeFWYZd/tmpg434FS -t ska_cab/tigger_tag /tmp/tmpeFWYZd
Sending build context to Docker daemon  12.29kB
Step 1/8 : FROM stimela/tigger:1.0.1
 ---> f071ebb14f65
Step 2/8 : MAINTAINER <sphemakh@gmail.com>
 ---> Using cache
 ---> ee6bbe9a0069
Step 3/8 : ADD src /scratch/code
 ---> Using cache
 ---> 4143faa7929a
Step 4/8 : ENV LOGFILE ${OUTPUT}/logfile.txt
 ---> Using cache
 ---> dc2270ed6f54
Step 5/8 : WORKDIR /home/ska/output/
 ---> Using cache
 ---> fac5b5151f4a
Step 6/8 : RUN useradd -r -u 1000 -U ska
 ---> Using cache
 ---> 644b6787b77e
Step 7/8 : USER ska
 ---> Using cache
 ---> a10882fdb9e2
Step 8/8 : CMD /scratch/code/run.sh
 ---> Using cache
 ---> ddb11aeaba4d
Successfully built ddb11aeaba4d
Successfully tagged ska_cab/tigger_tag:latest

Traceback (most recent call last):
  File "/home/ska/skavenv/bin/stimela", line 13, in <module>
    stimela.main([a for a in sys.argv[1:]])
  File "/home/ska/skavenv/local/lib/python2.7/site-packages/stimela/__init__.py", line 638, in main
    _cmd(argv)
  File "/home/ska/skavenv/local/lib/python2.7/site-packages/stimela/__init__.py", line 178, in build
    log.log_image(image, dockerfile, replace=True, cab=True)
  File "/home/ska/skavenv/local/lib/python2.7/site-packages/stimela/utils/logger.py", line 47, in log_image
    info = self._inspect(name)
  File "/home/ska/skavenv/local/lib/python2.7/site-packages/stimela/utils/logger.py", line 36, in _inspect
    output = subprocess.check_output("{0:s} inspect {1:s}".format(self.jtype, name), shell=True).decode()
  File "/usr/lib/python2.7/subprocess.py", line 219, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command 'udocker inspect ska_cab/tigger_tag' returned non-zero exit status 1
```
I'm surprised, because just before getting the error, there is a line saying that "ska_cab/tigger_tag" has been succesfully tagged, but it seems that's what causing problem to udocker. I tried to find something named "ska_cab" or "tigger_tab" with find command, but I didn't find anything.

Does anyone has an idea about this ?

**Comment by Popiette** [comment]
It was my fault, i didn't added the current user to docker group with usermod command, but with useradd.

Sorry for opening an issue for nothing...
