### ISSUE TITLE
Catdagger does not run within singularity

### ISSUE THREAD

**Issue by bennahugo** [SpheMakh/Stimela#420]
```
INFO:STIMELA:Adding cab '/home/hugo/STIMELA_IMAGES/stimela_pybdsf_1.0.1.img' to recipe. The container will be named 'find_sources'
Traceback (most recent call last):
  File "/home/hugo/venvstimela/bin/stimela", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "/home/hugo/stimela/bin/stimela", line 13, in <module>
    stimela.main([a for a in sys.argv[1:]])
  File "/home/hugo/stimela/stimela/__init__.py", line 638, in main
    _cmd(argv)
  File "/home/hugo/stimela/stimela/__init__.py", line 302, in run
    exec(stdr.read(), _globals)
  File "<string>", line 451, in <module>
  File "<string>", line 230, in sourcefind_and_subtract
  File "/home/hugo/stimela/stimela/recipe.py", line 667, in add
    time_out=time_out)
  File "/home/hugo/stimela/stimela/recipe.py", line 228, in singularity_job
    self.recipe.stimela_path, _cab.task), "/scratch/code", "ro")
  File "/home/hugo/stimela/stimela/singularity.py", line 62, in add_volume
    raise IOError("Path {0} cannot be mounted on container: File doesn't exist".format(host))
IOError: Path /home/hugo/stimela/stimela/cargo/cab/dagger/src/ cannot be mounted on container: File doesn't exist
```

**Comment by bennahugo** [comment]
Will submit a series of fixes soon
