### ISSUE TITLE
Crystalball  supports only circular DS9 region files

### ISSUE THREAD

**Issue by KshitijT** [SpheMakh/Stimela#459]
I am using Crystalball and running into this error:
```
Traceback (most recent call last):
  File "/usr/local/bin/crystalball", line 7, in <module>
    pkg.main([a for a in sys.argv[1:]])
  File "/usr/local/lib/python2.7/dist-packages/Crystalball/main.py", line 10, in main
    predictor.predict( p.parse_args() )
  File "/usr/local/lib/python2.7/dist-packages/Crystalball/crystalball.py", line 172, in predict
    num=args.num_sources or None)
  File "/usr/local/lib/python2.7/dist-packages/Crystalball/wsclean.py", line 88, in import_from_wsclean
    raise ValueError('Only circular DS( regions supported for now')
ValueError: Only circular DS( regions supported for now
```
While I am happy to make Circular region files, it might not be the best thing to do since radio sources are not guaranteed to be circular. 

If this is NOT a stimela issue, please let me know, will raise it on Crystalball repo.

**Comment by SpheMakh** [comment]
Yes, this is a crystalball issue
