### ISSUE TITLE
flagms does not report exit status

### ISSUE THREAD

**Issue by bennahugo** [SpheMakh/Stimela#54]
```
flag-ms.py: MS does not contain a BITFLAG column. Please run the addbitflagcol utility on this MS.
Process Process-2:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/utils/utils/__init__.py", line 103, in worker
    command(*args)
  File "/code/run.py", line 33, in flagms
    utils.xrun("flag-ms.py", flag_cmd+[export, ms])
  File "/utils/utils/__init__.py", line 71, in xrun
    raise SystemError('%s: returns errr code %d'%(command, process.returncode))
SystemError: flag-ms.py: returns errr code 1
running: docker rm clear_flags-148420406657
clear_flags-148420406657
running: docker create  -v /home/hugo/OPTSOFT/Stimela/stimela:/utils:ro -v /home/hugo/OPTSOFT/Stimela/stimela/cargo/data:/data:ro -v /home/hugo/DATASETS/msdir:/home/hugo/msdir:rw -v /home/hugo/DATASETS/output:/input:rw -v /home/hugo/DATASETS/output:/home/hugo/output:rw -v /home/hugo/DATASETS/configs:/configs:ro  -e MSDIR=/home/hugo/msdir -e INPUT=/input -e OUTPUT=/home/hugo/output -e CONFIG=/configs/imaging_pipeline-extract_sources_3-148420406657.json  --name extract_sources_3-148420406657 --shm-size 1gb hugo_cab/sourcery 
5dffb61ed80caf387ddc185f82355969116d52557f14ef35e9202022fb143f63
running: docker start -a extract_sources_3-148420406657

```

**Comment by SpheMakh** [comment]
Fixed in [formalise-cabs](https://github.com/SpheMakh/Stimela/commits/formalise-cabs)
