### ISSUE TITLE
ERROR if no sky model is specified

### ISSUE THREAD

**Issue by Athanaseus** [SpheMakh/Stimela#75]
Trying to run a noise simulation with no sky model specified.
I get the following error:

```
Traceback (most recent call last):
  File "/code/run.py", line 36, in <module>
    if not os.path.exists(skymodel):
  File "/usr/lib/python2.7/genericpath.py", line 26, in exists
    os.stat(path)
TypeError: coercing to Unicode: need string or buffer, NoneType found
```

**Comment by SpheMakh** [comment]
Fixed in https://github.com/SpheMakh/Stimela/commit/4470b284c4f1a9183f598186e7a3c0ad1c70ce35
