### ISSUE TITLE
Meqtrees base is defaulting to system cattery in /usr/lib

### ISSUE THREAD

**Issue by Sebokolodi** [SpheMakh/Stimela#99]
@SpheMakh With latest build of meqtrees base image we are noticed that meqtrees is using the system cattery even though the ENV MEQTREES_CATTERY_PATH is set to /usr/local/lib:
```
17.78 3.5Gb gainopts(StefCal.py:724:get_result): resetting data and model to initial values
17.78 3.5Gb gainopts(StefCal.py:751:get_result): ('0', '1') data type of data is complex64
17.78 3.5Gb gainopts(StefCal.py:752:get_result): ('0', '1') data type of model is complex64
17.78 3.5Gb gainopts(StefCal.py:777:get_result): G: solvable 1 from major loop 0 (current 0)
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/Cattery/Calico/OMS/StefCal/StefCal.py", line 783, in get_result
    flagged |= self.run_gain_solution(opt,model,data,weight,bitflags,flag_null_gains=True,looptype=looptype);
  File "/usr/lib/python2.7/dist-packages/Cattery/Calico/OMS/StefCal/StefCal.py", line 1271, in run_gain_solution
    self.compute_chisq(model,data,gopt.solver,weight=weight,bitflags=bitflags);
  File "/usr/lib/python2.7/dist-packages/Cattery/Calico/OMS/StefCal/StefCal.py", line 1201, in compute_chisq
    res = gain.residual(model,data,pq);
  File "/usr/lib/python2.7/dist-packages/Cattery/Calico/OMS/StefCal/Gain2x2.py", line 352, in residual
    c = self.apply(lhs,pq,cache=cache,tiler=tiler);
  File "/usr/lib/python2.7/dist-packages/Cattery/Calico/OMS/StefCal/Gain2x2.py", line 390, in apply
    lhs = self._get_matrix(p,q,lhs);
  File "/usr/lib/python2.7/dist-packages/Cattery/Calico/OMS/StefCal/Gain2x2.py", line 106, in _get_matrix
    return map(self._tile_complex_data,data[p,q]);
  File "/usr/lib/python2.7/dist-packages/Cattery/Calico/OMS/StefCal/Gain2x2.py", line 102, in _tile_complex_data
    return self.tile_data(x, dtype=self._dtype)
  File "/usr/lib/python2.7/dist-packages/Cattery/Calico/OMS/StefCal/DataTiler.py", line 50, in <lambda>
    self.tile_data = lambda x, dtype=None: x.astype(dtype) if ( dtype and dtype != x.dtype ) else x
AttributeError: 'int' object has no attribute 'dtype'
```
I believe setup.py's uninstall is deprecated and doesn't work so the solution would be to delete the system cattery before running pip install?

**Comment by SpheMakh** [comment]
I changed it to point to /usr/local because that's  where the updated Cattery is installed. Could you report this issue on [cattery](https://github.com/ska-sa/meqtrees-cattery)
